/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Option } from "./components/profile/raw-input-fields/Select";
import { RadioOption } from "./components/profile/raw-input-fields/RadioGroup";
import { MultiSelectOption } from "./components/profile/raw-input-fields/MultiSelect";
import { TokenResponse } from "@unidy.io/sdk-api-client";
export { Option } from "./components/profile/raw-input-fields/Select";
export { RadioOption } from "./components/profile/raw-input-fields/RadioGroup";
export { MultiSelectOption } from "./components/profile/raw-input-fields/MultiSelect";
export { TokenResponse } from "@unidy.io/sdk-api-client";
export namespace Components {
    interface UAuthProvider {
        /**
          * @default ""
         */
        "componentClassName": string;
    }
    interface UAuthSubmitButton {
        /**
          * @default ""
         */
        "componentClassName": string;
        /**
          * @default false
         */
        "disabled": boolean;
        "for": "email" | "password";
        /**
          * @default ""
         */
        "text": string;
    }
    interface UConditionalRender {
        "is": "true" | "false";
        "when": string;
    }
    interface UConfig {
        /**
          * @default ""
         */
        "apiKey": string;
        /**
          * @default ""
         */
        "baseUrl": string;
    }
    interface UEmailField {
        /**
          * @default ""
         */
        "componentClassName": string;
        /**
          * @default "Enter your email"
         */
        "placeholder": string;
    }
    interface UErrorMessage {
        /**
          * @default ""
         */
        "componentClassName": string;
        "errorMessages"?: Record<string, string>;
        "for": "email" | "password" | "magicCode" | "general";
    }
    interface UField {
        "componentClassName"?: string;
        /**
          * @default "label"
         */
        "countryCodeDisplayOption"?: "icon" | "label";
        /**
          * @default true
         */
        "emptyOption": boolean;
        "field": string;
        /**
          * @default "Please enter a valid phone number."
         */
        "invalidPhoneMessage": string;
        "placeholder"?: string;
        /**
          * @default ""
         */
        "readonlyPlaceholder": string;
        /**
          * @default false
         */
        "renderDefaultLabel": boolean;
        /**
          * @default false
         */
        "required": boolean;
    }
    interface UFlashMessage {
        /**
          * @default ""
         */
        "message": string;
        /**
          * @default "info"
         */
        "variant": "error" | "success" | "info";
    }
    interface ULogoutButton {
        /**
          * @default ""
         */
        "componentClassName": string;
        /**
          * @default true
         */
        "reloadOnSuccess": boolean;
        /**
          * @default "Logout"
         */
        "text": string;
    }
    interface UMagicCodeField {
        /**
          * @default ""
         */
        "componentClassName": string;
    }
    interface UMissingField {
    }
    interface UMissingFieldsSubmitButton {
    }
    interface UPasskey {
        /**
          * @default ""
         */
        "componentClassName": string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default "Authenticating..."
         */
        "loadingText": string;
        /**
          * @default "Sign in with Passkey"
         */
        "text": string;
    }
    interface UPasswordField {
        /**
          * @default ""
         */
        "componentClassName": string;
        /**
          * @default "Enter your password"
         */
        "placeholder": string;
    }
    interface UProfile {
        "apiKey"?: string;
        "apiUrl"?: string;
        /**
          * @default ""
         */
        "initialData": string | Record<string, string>;
        "language"?: string;
        "profileId"?: string;
    }
    interface UProfileSubmitButton {
    }
    interface URawField {
        "attrName"?: string;
        "checked"?: boolean;
        "componentClassName"?: string;
        /**
          * @default "label"
         */
        "countryCodeDisplayOption"?: "icon" | "label";
        "disabled"?: boolean;
        /**
          * @default false
         */
        "emptyOption": boolean;
        "field": string;
        /**
          * @default "Please enter a valid phone number."
         */
        "invalidPhoneMessage": string;
        "multiSelectOptions"?: MultiSelectOption[];
        "options"?: string | Option[];
        "placeholder"?: string;
        "radioOptions"?: RadioOption[];
        /**
          * @default ""
         */
        "readonlyPlaceholder": string;
        /**
          * @default false
         */
        "required": boolean;
        "specificPartKey"?: string;
        "tooltip"?: string;
        "type": string;
        "value"?: string | string[];
    }
    interface UResetPasswordButton {
        /**
          * @default ""
         */
        "componentClassName": string;
        /**
          * @default "Password reset email sent. Please check your inbox."
         */
        "successMessage": string;
        /**
          * @default "Reset Password"
         */
        "text": string;
    }
    interface USendMagicCodeButton {
        /**
          * @default "Magic code already sent to your email"
         */
        "alreadySentText": string;
        /**
          * @default ""
         */
        "componentClassName": string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default "Send Magic Code"
         */
        "text": string;
    }
    interface USigninRoot {
        /**
          * @default ""
         */
        "componentClassName": string;
    }
    interface USigninStep {
        /**
          * @default false
         */
        "alwaysRender": boolean;
        "isActive": () => Promise<boolean>;
        "name": "email" | "verification";
        "submit": () => Promise<void>;
    }
    interface USigninStrategy {
        /**
          * @default ""
         */
        "componentClassName": string;
        "type": "password" | "magic-code";
    }
    interface USocialLoginButton {
        /**
          * @default false
         */
        "iconOnly": boolean;
        /**
          * @default "google"
         */
        "provider": SocialLoginProvider;
        /**
          * @default window.location.href
         */
        "redirectUri": string;
        /**
          * @default "Continue with Google"
         */
        "text": string;
        /**
          * @default "light"
         */
        "theme": "light" | "dark";
    }
}
export interface ULogoutButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLULogoutButtonElement;
}
export interface USigninRootCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUSigninRootElement;
}
declare global {
    interface HTMLUAuthProviderElement extends Components.UAuthProvider, HTMLStencilElement {
    }
    var HTMLUAuthProviderElement: {
        prototype: HTMLUAuthProviderElement;
        new (): HTMLUAuthProviderElement;
    };
    interface HTMLUAuthSubmitButtonElement extends Components.UAuthSubmitButton, HTMLStencilElement {
    }
    var HTMLUAuthSubmitButtonElement: {
        prototype: HTMLUAuthSubmitButtonElement;
        new (): HTMLUAuthSubmitButtonElement;
    };
    interface HTMLUConditionalRenderElement extends Components.UConditionalRender, HTMLStencilElement {
    }
    var HTMLUConditionalRenderElement: {
        prototype: HTMLUConditionalRenderElement;
        new (): HTMLUConditionalRenderElement;
    };
    interface HTMLUConfigElement extends Components.UConfig, HTMLStencilElement {
    }
    var HTMLUConfigElement: {
        prototype: HTMLUConfigElement;
        new (): HTMLUConfigElement;
    };
    interface HTMLUEmailFieldElement extends Components.UEmailField, HTMLStencilElement {
    }
    var HTMLUEmailFieldElement: {
        prototype: HTMLUEmailFieldElement;
        new (): HTMLUEmailFieldElement;
    };
    interface HTMLUErrorMessageElement extends Components.UErrorMessage, HTMLStencilElement {
    }
    var HTMLUErrorMessageElement: {
        prototype: HTMLUErrorMessageElement;
        new (): HTMLUErrorMessageElement;
    };
    interface HTMLUFieldElement extends Components.UField, HTMLStencilElement {
    }
    var HTMLUFieldElement: {
        prototype: HTMLUFieldElement;
        new (): HTMLUFieldElement;
    };
    interface HTMLUFlashMessageElement extends Components.UFlashMessage, HTMLStencilElement {
    }
    var HTMLUFlashMessageElement: {
        prototype: HTMLUFlashMessageElement;
        new (): HTMLUFlashMessageElement;
    };
    interface HTMLULogoutButtonElementEventMap {
        "logout": void;
    }
    interface HTMLULogoutButtonElement extends Components.ULogoutButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLULogoutButtonElementEventMap>(type: K, listener: (this: HTMLULogoutButtonElement, ev: ULogoutButtonCustomEvent<HTMLULogoutButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLULogoutButtonElementEventMap>(type: K, listener: (this: HTMLULogoutButtonElement, ev: ULogoutButtonCustomEvent<HTMLULogoutButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLULogoutButtonElement: {
        prototype: HTMLULogoutButtonElement;
        new (): HTMLULogoutButtonElement;
    };
    interface HTMLUMagicCodeFieldElement extends Components.UMagicCodeField, HTMLStencilElement {
    }
    var HTMLUMagicCodeFieldElement: {
        prototype: HTMLUMagicCodeFieldElement;
        new (): HTMLUMagicCodeFieldElement;
    };
<<<<<<< HEAD
    interface HTMLUMissingFieldElement extends Components.UMissingField, HTMLStencilElement {
    }
    var HTMLUMissingFieldElement: {
        prototype: HTMLUMissingFieldElement;
        new (): HTMLUMissingFieldElement;
    };
    interface HTMLUMissingFieldsSubmitButtonElement extends Components.UMissingFieldsSubmitButton, HTMLStencilElement {
    }
    var HTMLUMissingFieldsSubmitButtonElement: {
        prototype: HTMLUMissingFieldsSubmitButtonElement;
        new (): HTMLUMissingFieldsSubmitButtonElement;
=======
    interface HTMLUPasskeyElement extends Components.UPasskey, HTMLStencilElement {
    }
    var HTMLUPasskeyElement: {
        prototype: HTMLUPasskeyElement;
        new (): HTMLUPasskeyElement;
>>>>>>> 3ffc7b20e4e4ab1031267bfa94b2eeb64d9efa06
    };
    interface HTMLUPasswordFieldElement extends Components.UPasswordField, HTMLStencilElement {
    }
    var HTMLUPasswordFieldElement: {
        prototype: HTMLUPasswordFieldElement;
        new (): HTMLUPasswordFieldElement;
    };
    interface HTMLUProfileElement extends Components.UProfile, HTMLStencilElement {
    }
    var HTMLUProfileElement: {
        prototype: HTMLUProfileElement;
        new (): HTMLUProfileElement;
    };
    interface HTMLUProfileSubmitButtonElement extends Components.UProfileSubmitButton, HTMLStencilElement {
    }
    var HTMLUProfileSubmitButtonElement: {
        prototype: HTMLUProfileSubmitButtonElement;
        new (): HTMLUProfileSubmitButtonElement;
    };
    interface HTMLURawFieldElement extends Components.URawField, HTMLStencilElement {
    }
    var HTMLURawFieldElement: {
        prototype: HTMLURawFieldElement;
        new (): HTMLURawFieldElement;
    };
    interface HTMLUResetPasswordButtonElement extends Components.UResetPasswordButton, HTMLStencilElement {
    }
    var HTMLUResetPasswordButtonElement: {
        prototype: HTMLUResetPasswordButtonElement;
        new (): HTMLUResetPasswordButtonElement;
    };
    interface HTMLUSendMagicCodeButtonElement extends Components.USendMagicCodeButton, HTMLStencilElement {
    }
    var HTMLUSendMagicCodeButtonElement: {
        prototype: HTMLUSendMagicCodeButtonElement;
        new (): HTMLUSendMagicCodeButtonElement;
    };
    interface HTMLUSigninRootElementEventMap {
        "authEvent": TokenResponse;
        "errorEvent": { error: string };
    }
    interface HTMLUSigninRootElement extends Components.USigninRoot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUSigninRootElementEventMap>(type: K, listener: (this: HTMLUSigninRootElement, ev: USigninRootCustomEvent<HTMLUSigninRootElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUSigninRootElementEventMap>(type: K, listener: (this: HTMLUSigninRootElement, ev: USigninRootCustomEvent<HTMLUSigninRootElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUSigninRootElement: {
        prototype: HTMLUSigninRootElement;
        new (): HTMLUSigninRootElement;
    };
    interface HTMLUSigninStepElement extends Components.USigninStep, HTMLStencilElement {
    }
    var HTMLUSigninStepElement: {
        prototype: HTMLUSigninStepElement;
        new (): HTMLUSigninStepElement;
    };
    interface HTMLUSigninStrategyElement extends Components.USigninStrategy, HTMLStencilElement {
    }
    var HTMLUSigninStrategyElement: {
        prototype: HTMLUSigninStrategyElement;
        new (): HTMLUSigninStrategyElement;
    };
    interface HTMLUSocialLoginButtonElement extends Components.USocialLoginButton, HTMLStencilElement {
    }
    var HTMLUSocialLoginButtonElement: {
        prototype: HTMLUSocialLoginButtonElement;
        new (): HTMLUSocialLoginButtonElement;
    };
    interface HTMLElementTagNameMap {
        "u-auth-provider": HTMLUAuthProviderElement;
        "u-auth-submit-button": HTMLUAuthSubmitButtonElement;
        "u-conditional-render": HTMLUConditionalRenderElement;
        "u-config": HTMLUConfigElement;
        "u-email-field": HTMLUEmailFieldElement;
        "u-error-message": HTMLUErrorMessageElement;
        "u-field": HTMLUFieldElement;
        "u-flash-message": HTMLUFlashMessageElement;
        "u-logout-button": HTMLULogoutButtonElement;
        "u-magic-code-field": HTMLUMagicCodeFieldElement;
<<<<<<< HEAD
        "u-missing-field": HTMLUMissingFieldElement;
        "u-missing-fields-submit-button": HTMLUMissingFieldsSubmitButtonElement;
=======
        "u-passkey": HTMLUPasskeyElement;
>>>>>>> 3ffc7b20e4e4ab1031267bfa94b2eeb64d9efa06
        "u-password-field": HTMLUPasswordFieldElement;
        "u-profile": HTMLUProfileElement;
        "u-profile-submit-button": HTMLUProfileSubmitButtonElement;
        "u-raw-field": HTMLURawFieldElement;
        "u-reset-password-button": HTMLUResetPasswordButtonElement;
        "u-send-magic-code-button": HTMLUSendMagicCodeButtonElement;
        "u-signin-root": HTMLUSigninRootElement;
        "u-signin-step": HTMLUSigninStepElement;
        "u-signin-strategy": HTMLUSigninStrategyElement;
        "u-social-login-button": HTMLUSocialLoginButtonElement;
    }
}
declare namespace LocalJSX {
    interface UAuthProvider {
        /**
          * @default ""
         */
        "componentClassName"?: string;
    }
    interface UAuthSubmitButton {
        /**
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "for": "email" | "password";
        /**
          * @default ""
         */
        "text"?: string;
    }
    interface UConditionalRender {
        "is": "true" | "false";
        "when": string;
    }
    interface UConfig {
        /**
          * @default ""
         */
        "apiKey"?: string;
        /**
          * @default ""
         */
        "baseUrl"?: string;
    }
    interface UEmailField {
        /**
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * @default "Enter your email"
         */
        "placeholder"?: string;
    }
    interface UErrorMessage {
        /**
          * @default ""
         */
        "componentClassName"?: string;
        "errorMessages"?: Record<string, string>;
        "for": "email" | "password" | "magicCode" | "general";
    }
    interface UField {
        "componentClassName"?: string;
        /**
          * @default "label"
         */
        "countryCodeDisplayOption"?: "icon" | "label";
        /**
          * @default true
         */
        "emptyOption"?: boolean;
        "field": string;
        /**
          * @default "Please enter a valid phone number."
         */
        "invalidPhoneMessage"?: string;
        "placeholder"?: string;
        /**
          * @default ""
         */
        "readonlyPlaceholder"?: string;
        /**
          * @default false
         */
        "renderDefaultLabel"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
    }
    interface UFlashMessage {
        /**
          * @default ""
         */
        "message"?: string;
        /**
          * @default "info"
         */
        "variant"?: "error" | "success" | "info";
    }
    interface ULogoutButton {
        /**
          * @default ""
         */
        "componentClassName"?: string;
        "onLogout"?: (event: ULogoutButtonCustomEvent<void>) => void;
        /**
          * @default true
         */
        "reloadOnSuccess"?: boolean;
        /**
          * @default "Logout"
         */
        "text"?: string;
    }
    interface UMagicCodeField {
        /**
          * @default ""
         */
        "componentClassName"?: string;
    }
<<<<<<< HEAD
    interface UMissingField {
    }
    interface UMissingFieldsSubmitButton {
=======
    interface UPasskey {
        /**
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default "Authenticating..."
         */
        "loadingText"?: string;
        /**
          * @default "Sign in with Passkey"
         */
        "text"?: string;
>>>>>>> 3ffc7b20e4e4ab1031267bfa94b2eeb64d9efa06
    }
    interface UPasswordField {
        /**
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * @default "Enter your password"
         */
        "placeholder"?: string;
    }
    interface UProfile {
        "apiKey"?: string;
        "apiUrl"?: string;
        /**
          * @default ""
         */
        "initialData"?: string | Record<string, string>;
        "language"?: string;
        "profileId"?: string;
    }
    interface UProfileSubmitButton {
    }
    interface URawField {
        "attrName"?: string;
        "checked"?: boolean;
        "componentClassName"?: string;
        /**
          * @default "label"
         */
        "countryCodeDisplayOption"?: "icon" | "label";
        "disabled"?: boolean;
        /**
          * @default false
         */
        "emptyOption"?: boolean;
        "field": string;
        /**
          * @default "Please enter a valid phone number."
         */
        "invalidPhoneMessage"?: string;
        "multiSelectOptions"?: MultiSelectOption[];
        "options"?: string | Option[];
        "placeholder"?: string;
        "radioOptions"?: RadioOption[];
        /**
          * @default ""
         */
        "readonlyPlaceholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        "specificPartKey"?: string;
        "tooltip"?: string;
        "type": string;
        "value"?: string | string[];
    }
    interface UResetPasswordButton {
        /**
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * @default "Password reset email sent. Please check your inbox."
         */
        "successMessage"?: string;
        /**
          * @default "Reset Password"
         */
        "text"?: string;
    }
    interface USendMagicCodeButton {
        /**
          * @default "Magic code already sent to your email"
         */
        "alreadySentText"?: string;
        /**
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default "Send Magic Code"
         */
        "text"?: string;
    }
    interface USigninRoot {
        /**
          * @default ""
         */
        "componentClassName"?: string;
        "onAuthEvent"?: (event: USigninRootCustomEvent<TokenResponse>) => void;
        "onErrorEvent"?: (event: USigninRootCustomEvent<{ error: string }>) => void;
    }
    interface USigninStep {
        /**
          * @default false
         */
        "alwaysRender"?: boolean;
        "name": "email" | "verification";
    }
    interface USigninStrategy {
        /**
          * @default ""
         */
        "componentClassName"?: string;
        "type": "password" | "magic-code";
    }
    interface USocialLoginButton {
        /**
          * @default false
         */
        "iconOnly"?: boolean;
        /**
          * @default "google"
         */
        "provider"?: SocialLoginProvider;
        /**
          * @default window.location.href
         */
        "redirectUri"?: string;
        /**
          * @default "Continue with Google"
         */
        "text"?: string;
        /**
          * @default "light"
         */
        "theme"?: "light" | "dark";
    }
    interface IntrinsicElements {
        "u-auth-provider": UAuthProvider;
        "u-auth-submit-button": UAuthSubmitButton;
        "u-conditional-render": UConditionalRender;
        "u-config": UConfig;
        "u-email-field": UEmailField;
        "u-error-message": UErrorMessage;
        "u-field": UField;
        "u-flash-message": UFlashMessage;
        "u-logout-button": ULogoutButton;
        "u-magic-code-field": UMagicCodeField;
<<<<<<< HEAD
        "u-missing-field": UMissingField;
        "u-missing-fields-submit-button": UMissingFieldsSubmitButton;
=======
        "u-passkey": UPasskey;
>>>>>>> 3ffc7b20e4e4ab1031267bfa94b2eeb64d9efa06
        "u-password-field": UPasswordField;
        "u-profile": UProfile;
        "u-profile-submit-button": UProfileSubmitButton;
        "u-raw-field": URawField;
        "u-reset-password-button": UResetPasswordButton;
        "u-send-magic-code-button": USendMagicCodeButton;
        "u-signin-root": USigninRoot;
        "u-signin-step": USigninStep;
        "u-signin-strategy": USigninStrategy;
        "u-social-login-button": USocialLoginButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "u-auth-provider": LocalJSX.UAuthProvider & JSXBase.HTMLAttributes<HTMLUAuthProviderElement>;
            "u-auth-submit-button": LocalJSX.UAuthSubmitButton & JSXBase.HTMLAttributes<HTMLUAuthSubmitButtonElement>;
            "u-conditional-render": LocalJSX.UConditionalRender & JSXBase.HTMLAttributes<HTMLUConditionalRenderElement>;
            "u-config": LocalJSX.UConfig & JSXBase.HTMLAttributes<HTMLUConfigElement>;
            "u-email-field": LocalJSX.UEmailField & JSXBase.HTMLAttributes<HTMLUEmailFieldElement>;
            "u-error-message": LocalJSX.UErrorMessage & JSXBase.HTMLAttributes<HTMLUErrorMessageElement>;
            "u-field": LocalJSX.UField & JSXBase.HTMLAttributes<HTMLUFieldElement>;
            "u-flash-message": LocalJSX.UFlashMessage & JSXBase.HTMLAttributes<HTMLUFlashMessageElement>;
            "u-logout-button": LocalJSX.ULogoutButton & JSXBase.HTMLAttributes<HTMLULogoutButtonElement>;
            "u-magic-code-field": LocalJSX.UMagicCodeField & JSXBase.HTMLAttributes<HTMLUMagicCodeFieldElement>;
<<<<<<< HEAD
            "u-missing-field": LocalJSX.UMissingField & JSXBase.HTMLAttributes<HTMLUMissingFieldElement>;
            "u-missing-fields-submit-button": LocalJSX.UMissingFieldsSubmitButton & JSXBase.HTMLAttributes<HTMLUMissingFieldsSubmitButtonElement>;
=======
            "u-passkey": LocalJSX.UPasskey & JSXBase.HTMLAttributes<HTMLUPasskeyElement>;
>>>>>>> 3ffc7b20e4e4ab1031267bfa94b2eeb64d9efa06
            "u-password-field": LocalJSX.UPasswordField & JSXBase.HTMLAttributes<HTMLUPasswordFieldElement>;
            "u-profile": LocalJSX.UProfile & JSXBase.HTMLAttributes<HTMLUProfileElement>;
            "u-profile-submit-button": LocalJSX.UProfileSubmitButton & JSXBase.HTMLAttributes<HTMLUProfileSubmitButtonElement>;
            "u-raw-field": LocalJSX.URawField & JSXBase.HTMLAttributes<HTMLURawFieldElement>;
            "u-reset-password-button": LocalJSX.UResetPasswordButton & JSXBase.HTMLAttributes<HTMLUResetPasswordButtonElement>;
            "u-send-magic-code-button": LocalJSX.USendMagicCodeButton & JSXBase.HTMLAttributes<HTMLUSendMagicCodeButtonElement>;
            "u-signin-root": LocalJSX.USigninRoot & JSXBase.HTMLAttributes<HTMLUSigninRootElement>;
            "u-signin-step": LocalJSX.USigninStep & JSXBase.HTMLAttributes<HTMLUSigninStepElement>;
            "u-signin-strategy": LocalJSX.USigninStrategy & JSXBase.HTMLAttributes<HTMLUSigninStrategyElement>;
            "u-social-login-button": LocalJSX.USocialLoginButton & JSXBase.HTMLAttributes<HTMLUSocialLoginButtonElement>;
        }
    }
}
