/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TokenResponse } from "@unidy.io/sdk-api-client";
export { TokenResponse } from "@unidy.io/sdk-api-client";
export namespace Components {
    interface EmailField {
        /**
          * @default ""
         */
        "className": string;
        /**
          * @default "Enter your email"
         */
        "placeholder": string;
    }
    interface PasswordField {
        /**
          * @default ""
         */
        "className": string;
        /**
          * @default "Enter your password"
         */
        "placeholder": string;
    }
    interface SigninRoot {
        /**
          * @default ""
         */
        "apiKey": string;
        /**
          * @default ""
         */
        "baseUrl": string;
        /**
          * @default ""
         */
        "className": string;
    }
    interface SubmitButton {
        /**
          * @default ""
         */
        "className": string;
        /**
          * @default false
         */
        "disabled": boolean;
    }
}
export interface SigninRootCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSigninRootElement;
}
declare global {
    interface HTMLEmailFieldElement extends Components.EmailField, HTMLStencilElement {
    }
    var HTMLEmailFieldElement: {
        prototype: HTMLEmailFieldElement;
        new (): HTMLEmailFieldElement;
    };
    interface HTMLPasswordFieldElement extends Components.PasswordField, HTMLStencilElement {
    }
    var HTMLPasswordFieldElement: {
        prototype: HTMLPasswordFieldElement;
        new (): HTMLPasswordFieldElement;
    };
    interface HTMLSigninRootElementEventMap {
        "authEvent": TokenResponse;
        "errorEvent": string;
    }
    interface HTMLSigninRootElement extends Components.SigninRoot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSigninRootElementEventMap>(type: K, listener: (this: HTMLSigninRootElement, ev: SigninRootCustomEvent<HTMLSigninRootElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSigninRootElementEventMap>(type: K, listener: (this: HTMLSigninRootElement, ev: SigninRootCustomEvent<HTMLSigninRootElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSigninRootElement: {
        prototype: HTMLSigninRootElement;
        new (): HTMLSigninRootElement;
    };
    interface HTMLSubmitButtonElement extends Components.SubmitButton, HTMLStencilElement {
    }
    var HTMLSubmitButtonElement: {
        prototype: HTMLSubmitButtonElement;
        new (): HTMLSubmitButtonElement;
    };
    interface HTMLElementTagNameMap {
        "email-field": HTMLEmailFieldElement;
        "password-field": HTMLPasswordFieldElement;
        "signin-root": HTMLSigninRootElement;
        "submit-button": HTMLSubmitButtonElement;
    }
}
declare namespace LocalJSX {
    interface EmailField {
        /**
          * @default ""
         */
        "className"?: string;
        /**
          * @default "Enter your email"
         */
        "placeholder"?: string;
    }
    interface PasswordField {
        /**
          * @default ""
         */
        "className"?: string;
        /**
          * @default "Enter your password"
         */
        "placeholder"?: string;
    }
    interface SigninRoot {
        /**
          * @default ""
         */
        "apiKey"?: string;
        /**
          * @default ""
         */
        "baseUrl"?: string;
        /**
          * @default ""
         */
        "className"?: string;
        "onAuthEvent"?: (event: SigninRootCustomEvent<TokenResponse>) => void;
        "onErrorEvent"?: (event: SigninRootCustomEvent<string>) => void;
    }
    interface SubmitButton {
        /**
          * @default ""
         */
        "className"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
    }
    interface IntrinsicElements {
        "email-field": EmailField;
        "password-field": PasswordField;
        "signin-root": SigninRoot;
        "submit-button": SubmitButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "email-field": LocalJSX.EmailField & JSXBase.HTMLAttributes<HTMLEmailFieldElement>;
            "password-field": LocalJSX.PasswordField & JSXBase.HTMLAttributes<HTMLPasswordFieldElement>;
            "signin-root": LocalJSX.SigninRoot & JSXBase.HTMLAttributes<HTMLSigninRootElement>;
            "submit-button": LocalJSX.SubmitButton & JSXBase.HTMLAttributes<HTMLSubmitButtonElement>;
        }
    }
}
