/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ObservableMap } from "@stencil/store";
import { ProfileStore } from "./components/unidy-profile/unidy-profile";
export { ObservableMap } from "@stencil/store";
export { ProfileStore } from "./components/unidy-profile/unidy-profile";
export namespace Components {
    interface AuthProvider {
    }
    interface ConditionalRender {
        "is": "true" | "false";
        "when": string;
    }
    interface EmailField {
        /**
          * @default ""
         */
        "className": string;
        /**
          * @default "Enter your email"
         */
        "placeholder": string;
    }
    interface ErrorMessage {
        /**
          * @default ""
         */
        "className": string;
        "for": "email" | "magicCode" | "password";
    }
    interface FlashMessage {
        /**
          * @default ""
         */
        "message": string;
        /**
          * @default "info"
         */
        "variant": "error" | "success" | "info";
    }
    interface MagicCodeField {
        /**
          * @default ""
         */
        "className": string;
    }
    interface PasswordField {
        /**
          * @default ""
         */
        "className": string;
        /**
          * @default "Enter your password"
         */
        "placeholder": string;
    }
    interface SendMagicCodeButton {
        /**
          * @default ""
         */
        "className": string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default "Send Magic Code"
         */
        "text": string;
    }
    interface SigninRoot {
        /**
          * @default ""
         */
        "apiKey": string;
        /**
          * @default ""
         */
        "baseUrl": string;
        /**
          * @default ""
         */
        "className": string;
    }
    interface SigninStep {
        /**
          * @default false
         */
        "alwaysRender": boolean;
        "isActive": () => Promise<boolean>;
        "name": "email" | "verification";
    }
    interface SigninStrategy {
        /**
          * @default ""
         */
        "className": string;
        "type": "password" | "magic-code";
    }
    interface SubmitButton {
        /**
          * @default ""
         */
        "className": string;
        /**
          * @default false
         */
        "disabled": boolean;
        "for": "email" | "password";
        /**
          * @default ""
         */
        "text": string;
    }
    interface UnidyField {
        /**
          * @default "label"
         */
        "countryCodeDisplayOption"?: "icon" | "label";
        "field": string;
        /**
          * @default "Please enter a valid phone number."
         */
        "invalidPhoneMessage": string;
        /**
          * @default ""
         */
        "readonlyPlaceholder": string;
        /**
          * @default false
         */
        "required": boolean;
    }
    interface UnidyProfile {
        "apiKey"?: string;
        "apiUrl"?: string;
        /**
          * @default ""
         */
        "initialData": string | Record<string, string>;
        "language"?: string;
        "profileId"?: string;
        /**
          * @default createStore<ProfileStore>({     loading: true,     data: {},     configuration: {},     errors: {},     idToken: "",     client: undefined,     flashErrors: {},     language: "",     phoneValid: true,   })
         */
        "store": ObservableMap<ProfileStore>;
    }
    interface UnidySubmitButton {
    }
}
export interface SigninRootCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSigninRootElement;
}
declare global {
    interface HTMLAuthProviderElement extends Components.AuthProvider, HTMLStencilElement {
    }
    var HTMLAuthProviderElement: {
        prototype: HTMLAuthProviderElement;
        new (): HTMLAuthProviderElement;
    };
    interface HTMLConditionalRenderElement extends Components.ConditionalRender, HTMLStencilElement {
    }
    var HTMLConditionalRenderElement: {
        prototype: HTMLConditionalRenderElement;
        new (): HTMLConditionalRenderElement;
    };
    interface HTMLEmailFieldElement extends Components.EmailField, HTMLStencilElement {
    }
    var HTMLEmailFieldElement: {
        prototype: HTMLEmailFieldElement;
        new (): HTMLEmailFieldElement;
    };
    interface HTMLErrorMessageElement extends Components.ErrorMessage, HTMLStencilElement {
    }
    var HTMLErrorMessageElement: {
        prototype: HTMLErrorMessageElement;
        new (): HTMLErrorMessageElement;
    };
    interface HTMLFlashMessageElement extends Components.FlashMessage, HTMLStencilElement {
    }
    var HTMLFlashMessageElement: {
        prototype: HTMLFlashMessageElement;
        new (): HTMLFlashMessageElement;
    };
    interface HTMLMagicCodeFieldElement extends Components.MagicCodeField, HTMLStencilElement {
    }
    var HTMLMagicCodeFieldElement: {
        prototype: HTMLMagicCodeFieldElement;
        new (): HTMLMagicCodeFieldElement;
    };
    interface HTMLPasswordFieldElement extends Components.PasswordField, HTMLStencilElement {
    }
    var HTMLPasswordFieldElement: {
        prototype: HTMLPasswordFieldElement;
        new (): HTMLPasswordFieldElement;
    };
    interface HTMLSendMagicCodeButtonElement extends Components.SendMagicCodeButton, HTMLStencilElement {
    }
    var HTMLSendMagicCodeButtonElement: {
        prototype: HTMLSendMagicCodeButtonElement;
        new (): HTMLSendMagicCodeButtonElement;
    };
    interface HTMLSigninRootElementEventMap {
        "authEvent": TokenResponse;
        "errorEvent": { error: string };
    }
    interface HTMLSigninRootElement extends Components.SigninRoot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSigninRootElementEventMap>(type: K, listener: (this: HTMLSigninRootElement, ev: SigninRootCustomEvent<HTMLSigninRootElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSigninRootElementEventMap>(type: K, listener: (this: HTMLSigninRootElement, ev: SigninRootCustomEvent<HTMLSigninRootElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSigninRootElement: {
        prototype: HTMLSigninRootElement;
        new (): HTMLSigninRootElement;
    };
    interface HTMLSigninStepElement extends Components.SigninStep, HTMLStencilElement {
    }
    var HTMLSigninStepElement: {
        prototype: HTMLSigninStepElement;
        new (): HTMLSigninStepElement;
    };
    interface HTMLSigninStrategyElement extends Components.SigninStrategy, HTMLStencilElement {
    }
    var HTMLSigninStrategyElement: {
        prototype: HTMLSigninStrategyElement;
        new (): HTMLSigninStrategyElement;
    };
    interface HTMLSubmitButtonElement extends Components.SubmitButton, HTMLStencilElement {
    }
    var HTMLSubmitButtonElement: {
        prototype: HTMLSubmitButtonElement;
        new (): HTMLSubmitButtonElement;
    };
    interface HTMLUnidyFieldElement extends Components.UnidyField, HTMLStencilElement {
    }
    var HTMLUnidyFieldElement: {
        prototype: HTMLUnidyFieldElement;
        new (): HTMLUnidyFieldElement;
    };
    interface HTMLUnidyProfileElement extends Components.UnidyProfile, HTMLStencilElement {
    }
    var HTMLUnidyProfileElement: {
        prototype: HTMLUnidyProfileElement;
        new (): HTMLUnidyProfileElement;
    };
    interface HTMLUnidySubmitButtonElement extends Components.UnidySubmitButton, HTMLStencilElement {
    }
    var HTMLUnidySubmitButtonElement: {
        prototype: HTMLUnidySubmitButtonElement;
        new (): HTMLUnidySubmitButtonElement;
    };
    interface HTMLElementTagNameMap {
        "auth-provider": HTMLAuthProviderElement;
        "conditional-render": HTMLConditionalRenderElement;
        "email-field": HTMLEmailFieldElement;
        "error-message": HTMLErrorMessageElement;
        "flash-message": HTMLFlashMessageElement;
        "magic-code-field": HTMLMagicCodeFieldElement;
        "password-field": HTMLPasswordFieldElement;
        "send-magic-code-button": HTMLSendMagicCodeButtonElement;
        "signin-root": HTMLSigninRootElement;
        "signin-step": HTMLSigninStepElement;
        "signin-strategy": HTMLSigninStrategyElement;
        "submit-button": HTMLSubmitButtonElement;
        "unidy-field": HTMLUnidyFieldElement;
        "unidy-profile": HTMLUnidyProfileElement;
        "unidy-submit-button": HTMLUnidySubmitButtonElement;
    }
}
declare namespace LocalJSX {
    interface AuthProvider {
    }
    interface ConditionalRender {
        "is": "true" | "false";
        "when": string;
    }
    interface EmailField {
        /**
          * @default ""
         */
        "className"?: string;
        /**
          * @default "Enter your email"
         */
        "placeholder"?: string;
    }
    interface ErrorMessage {
        /**
          * @default ""
         */
        "className"?: string;
        "for": "email" | "magicCode" | "password";
    }
    interface FlashMessage {
        /**
          * @default ""
         */
        "message"?: string;
        /**
          * @default "info"
         */
        "variant"?: "error" | "success" | "info";
    }
    interface MagicCodeField {
        /**
          * @default ""
         */
        "className"?: string;
    }
    interface PasswordField {
        /**
          * @default ""
         */
        "className"?: string;
        /**
          * @default "Enter your password"
         */
        "placeholder"?: string;
    }
    interface SendMagicCodeButton {
        /**
          * @default ""
         */
        "className"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default "Send Magic Code"
         */
        "text"?: string;
    }
    interface SigninRoot {
        /**
          * @default ""
         */
        "apiKey"?: string;
        /**
          * @default ""
         */
        "baseUrl"?: string;
        /**
          * @default ""
         */
        "className"?: string;
        "onAuthEvent"?: (event: SigninRootCustomEvent<TokenResponse>) => void;
        "onErrorEvent"?: (event: SigninRootCustomEvent<{ error: string }>) => void;
    }
    interface SigninStep {
        /**
          * @default false
         */
        "alwaysRender"?: boolean;
        "name": "email" | "verification";
    }
    interface SigninStrategy {
        /**
          * @default ""
         */
        "className"?: string;
        "type": "password" | "magic-code";
    }
    interface SubmitButton {
        /**
          * @default ""
         */
        "className"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "for": "email" | "password";
        /**
          * @default ""
         */
        "text"?: string;
    }
    interface UnidyField {
        /**
          * @default "label"
         */
        "countryCodeDisplayOption"?: "icon" | "label";
        "field": string;
        /**
          * @default "Please enter a valid phone number."
         */
        "invalidPhoneMessage"?: string;
        /**
          * @default ""
         */
        "readonlyPlaceholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
    }
    interface UnidyProfile {
        "apiKey"?: string;
        "apiUrl"?: string;
        /**
          * @default ""
         */
        "initialData"?: string | Record<string, string>;
        "language"?: string;
        "profileId"?: string;
        /**
          * @default createStore<ProfileStore>({     loading: true,     data: {},     configuration: {},     errors: {},     idToken: "",     client: undefined,     flashErrors: {},     language: "",     phoneValid: true,   })
         */
        "store"?: ObservableMap<ProfileStore>;
    }
    interface UnidySubmitButton {
    }
    interface IntrinsicElements {
        "auth-provider": AuthProvider;
        "conditional-render": ConditionalRender;
        "email-field": EmailField;
        "error-message": ErrorMessage;
        "flash-message": FlashMessage;
        "magic-code-field": MagicCodeField;
        "password-field": PasswordField;
        "send-magic-code-button": SendMagicCodeButton;
        "signin-root": SigninRoot;
        "signin-step": SigninStep;
        "signin-strategy": SigninStrategy;
        "submit-button": SubmitButton;
        "unidy-field": UnidyField;
        "unidy-profile": UnidyProfile;
        "unidy-submit-button": UnidySubmitButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "auth-provider": LocalJSX.AuthProvider & JSXBase.HTMLAttributes<HTMLAuthProviderElement>;
            "conditional-render": LocalJSX.ConditionalRender & JSXBase.HTMLAttributes<HTMLConditionalRenderElement>;
            "email-field": LocalJSX.EmailField & JSXBase.HTMLAttributes<HTMLEmailFieldElement>;
            "error-message": LocalJSX.ErrorMessage & JSXBase.HTMLAttributes<HTMLErrorMessageElement>;
            "flash-message": LocalJSX.FlashMessage & JSXBase.HTMLAttributes<HTMLFlashMessageElement>;
            "magic-code-field": LocalJSX.MagicCodeField & JSXBase.HTMLAttributes<HTMLMagicCodeFieldElement>;
            "password-field": LocalJSX.PasswordField & JSXBase.HTMLAttributes<HTMLPasswordFieldElement>;
            "send-magic-code-button": LocalJSX.SendMagicCodeButton & JSXBase.HTMLAttributes<HTMLSendMagicCodeButtonElement>;
            "signin-root": LocalJSX.SigninRoot & JSXBase.HTMLAttributes<HTMLSigninRootElement>;
            "signin-step": LocalJSX.SigninStep & JSXBase.HTMLAttributes<HTMLSigninStepElement>;
            "signin-strategy": LocalJSX.SigninStrategy & JSXBase.HTMLAttributes<HTMLSigninStrategyElement>;
            "submit-button": LocalJSX.SubmitButton & JSXBase.HTMLAttributes<HTMLSubmitButtonElement>;
            "unidy-field": LocalJSX.UnidyField & JSXBase.HTMLAttributes<HTMLUnidyFieldElement>;
            "unidy-profile": LocalJSX.UnidyProfile & JSXBase.HTMLAttributes<HTMLUnidyProfileElement>;
            "unidy-submit-button": LocalJSX.UnidySubmitButton & JSXBase.HTMLAttributes<HTMLUnidySubmitButtonElement>;
        }
    }
}
