/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AuthState } from "./auth/store/auth-store";
import { Config, ConfigChange } from "./shared/components/config/config";
import { NewsletterButtonFor } from "./newsletter/components/submit-button/newsletter-submit-button";
import { PasswordFieldFor } from "./auth/components/password-field/password-field";
import { ProfileRaw } from "./profile/store/profile-store";
import { Option } from "./profile/components/raw-input-fields/Select";
import { RadioOption } from "./profile/components/raw-input-fields/RadioGroup";
import { MultiSelectOption } from "./profile/components/raw-input-fields/MultiSelect";
import { TokenResponse } from "./auth/api/auth";
import { AuthButtonFor } from "./auth/components/submit-button/auth-submit-button";
import { ExportFormat } from "./ticketable/api/schemas";
import { PaginationMeta } from "./api";
import { PaginationStore } from "./ticketable/store/pagination-store";
import { Subscription } from "./ticketable/api/subscriptions";
import { Ticket } from "./ticketable/api/tickets";
export { AuthState } from "./auth/store/auth-store";
export { Config, ConfigChange } from "./shared/components/config/config";
export { NewsletterButtonFor } from "./newsletter/components/submit-button/newsletter-submit-button";
export { PasswordFieldFor } from "./auth/components/password-field/password-field";
export { ProfileRaw } from "./profile/store/profile-store";
export { Option } from "./profile/components/raw-input-fields/Select";
export { RadioOption } from "./profile/components/raw-input-fields/RadioGroup";
export { MultiSelectOption } from "./profile/components/raw-input-fields/MultiSelect";
export { TokenResponse } from "./auth/api/auth";
export { AuthButtonFor } from "./auth/components/submit-button/auth-submit-button";
export { ExportFormat } from "./ticketable/api/schemas";
export { PaginationMeta } from "./api";
export { PaginationStore } from "./ticketable/store/pagination-store";
export { Subscription } from "./ticketable/api/subscriptions";
export { Ticket } from "./ticketable/api/tickets";
export namespace Components {
    interface UBackButton {
        /**
          * @default ""
         */
        "componentClassName": string;
        /**
          * If true, restarts the entire flow instead of going back one step. Use this for "Start over" buttons.
          * @default false
         */
        "restart": boolean;
    }
    interface UConditionalRender {
        "conditionFunction"?: (state: AuthState) => boolean;
        "is"?: string;
        /**
          * @default false
         */
        "not": boolean;
        "when"?: string;
    }
    interface UConfig {
        /**
          * Your Unidy API key.
          * @default ""
         */
        "apiKey": string;
        /**
          * The Unidy API base URL (e.g., 'https://your-tenant.unidy.io').
          * @default ""
         */
        "baseUrl": string;
        /**
          * If true, checks for existing session on load and restores authentication state.
          * @default false
         */
        "checkSignedIn": boolean;
        /**
          * Custom translations as JSON string or object. Keyed by locale code.
          * @default ""
         */
        "customTranslations": string | Record<string, TranslationTree>;
        /**
          * Fallback locale when translation is missing.
          * @default "en"
         */
        "fallbackLocale": string;
        /**
          * Current locale for translations (e.g., 'en', 'de', 'fr').
          * @default "en"
         */
        "locale": string;
        /**
          * SDK mode: 'production' or 'development'. Development mode enables verbose logging.
          * @default "production"
         */
        "mode": "production" | "development";
    }
    interface UEmailField {
        /**
          * ARIA label for accessibility.
          * @default "Email"
         */
        "ariaLabel": string;
        /**
          * CSS classes to apply to the input element.
          * @default ""
         */
        "componentClassName": string;
        /**
          * If true, the input will be disabled.
          * @default false
         */
        "disabled": boolean;
    }
    interface UErrorMessage {
        /**
          * CSS classes to apply to the host element.
          * @default ""
         */
        "componentClassName": string;
        /**
          * Custom error messages keyed by error code. Overrides default translations.
         */
        "errorMessages"?: Record<string, string>;
        /**
          * The error type to display (e.g., 'email', 'password', 'general', 'connection').
         */
        "for": string;
    }
    interface UField {
        /**
          * CSS classes to apply to the input element.
         */
        "componentClassName"?: string;
        /**
          * For phone fields: how to display country code selector ('icon' or 'label').
          * @default "label"
         */
        "countryCodeDisplayOption"?: "icon" | "label";
        /**
          * If true, includes an empty option in select dropdowns.
          * @default true
         */
        "emptyOption": boolean;
        /**
          * The field name (e.g., 'first_name', 'custom_attributes.favorite_color').
         */
        "field": string;
        /**
          * Error message shown when phone number validation fails.
          * @default "Please enter a valid phone number."
         */
        "invalidPhoneMessage": string;
        /**
          * Regex pattern for custom validation.
         */
        "pattern"?: string;
        /**
          * Error message shown when pattern validation fails.
         */
        "patternErrorMessage"?: string;
        /**
          * Placeholder text for the input field.
         */
        "placeholder"?: string;
        /**
          * Placeholder text shown when field is readonly and has no value.
          * @default "No information"
         */
        "readonlyPlaceholder": string;
        /**
          * If true, renders the default label above the field.
          * @default true
         */
        "renderDefaultLabel": boolean;
        /**
          * If true, marks the field as required (in addition to backend configuration).
          * @default false
         */
        "required": boolean;
        /**
          * Custom validation function. Returns { valid: boolean, message?: string }.
         */
        "validationFunc"?: (value: string | string[]) => { valid: boolean; message?: string };
    }
    interface UFlashMessage {
        /**
          * @default ""
         */
        "componentClassName": string;
        /**
          * @default null
         */
        "removeAfterSeconds": number | null;
    }
    interface UFullProfile {
        /**
          * For phone fields: how to display country code selector ('icon' or 'label').
          * @default "label"
         */
        "countryCodeDisplayOption"?: "icon" | "label";
        /**
          * Comma-separated list of field names to display. If not provided, shows all fields.
         */
        "fields"?: string;
    }
    interface UJumpToService {
        /**
          * Custom CSS class name(s) to apply to the button element.
          * @default ""
         */
        "componentClassName": string;
        /**
          * If true, opens the URL in a new tab. Defaults to false.
          * @default false
         */
        "newtab": boolean;
        /**
          * Optional redirect URI for the OAuth flow. Must match one of the application's allowed redirect URIs.
         */
        "redirectUri"?: string;
        /**
          * Comma-separated list of OAuth scopes to request. Defaults to ["openid"] if not provided.
          * @example "openid,profile"
         */
        "scopes"?: string;
        /**
          * The OAuth Application ID (service ID) to jump to.
          * @example "2"
         */
        "serviceId": string;
        /**
          * If true, skips the OAuth authorization step (if already authorized once). Defaults to false.
          * @default false
         */
        "skipOauthAuthorization": boolean;
    }
    interface UJumpToUnidy {
        /**
          * Custom CSS class name(s) to apply to the button element.
          * @default ""
         */
        "componentClassName": string;
        /**
          * If true, opens the URL in a new tab. Defaults to false.
          * @default false
         */
        "newtab": boolean;
        /**
          * If true, skips authentication and redirects directly to the Unidy path. Useful for public pages like terms of service.
          * @default false
         */
        "noAuth": boolean;
        /**
          * The Unidy path to redirect to. Must start with "/".
          * @example "/subscriptions"
          * @example "/tickets"
         */
        "path": string;
    }
    interface ULogoutButton {
        /**
          * CSS classes to apply to the button element.
          * @default ""
         */
        "componentClassName": string;
        /**
          * If true, reloads the page after successful logout.
          * @default true
         */
        "reloadOnSuccess": boolean;
    }
    interface UMagicCodeField {
        /**
          * CSS classes to apply to the container element.
          * @default ""
         */
        "componentClassName": string;
    }
    interface UMissingField {
        "componentClassName"?: string;
    }
    interface UMissingFieldsSubmitButton {
        /**
          * @default ""
         */
        "componentClassName": string;
    }
    interface UNewsletterCheckbox {
        /**
          * If true, the checkbox will be checked by default.
          * @default false
         */
        "checked": boolean;
        /**
          * CSS classes to apply to the checkbox element.
         */
        "componentClassName"?: string;
        /**
          * The internal name of the newsletter (as configured in the backend).
         */
        "internalName": string;
        /**
          * Public method to set the checkbox state programmatically
         */
        "setChecked": (checked: boolean) => Promise<void>;
        /**
          * Public method to toggle the checkbox programmatically
         */
        "toggle": () => Promise<void>;
    }
    interface UNewsletterConsentCheckbox {
        /**
          * CSS classes to apply to the checkbox element.
         */
        "componentClassName"?: string;
        "setChecked": (checked: boolean) => Promise<void>;
        "toggle": () => Promise<void>;
    }
    interface UNewsletterLogoutButton {
        /**
          * @default ""
         */
        "componentClassName": string;
    }
    interface UNewsletterPreferenceCheckbox {
        /**
          * If true, the checkbox will be checked by default.
          * @default false
         */
        "checked": boolean;
        /**
          * CSS classes to apply to the checkbox element.
         */
        "componentClassName"?: string;
        /**
          * The internal name of the parent newsletter.
         */
        "internalName": string;
        /**
          * The preference identifier (e.g., 'daily', 'weekly', 'promotions').
         */
        "preferenceIdentifier": string;
        /**
          * Public method to set the checkbox state programmatically
         */
        "setChecked": (checked: boolean) => Promise<void>;
        /**
          * Public method to toggle the checkbox programmatically
         */
        "toggle": () => Promise<void>;
    }
    interface UNewsletterResendDoiButton {
        /**
          * @default ""
         */
        "componentClassName": string;
        "internalName": string;
    }
    interface UNewsletterRoot {
        /**
          * CSS classes to apply to the host element.
          * @default ""
         */
        "componentClassName": string;
        "submit": (forType?: NewsletterButtonFor) => Promise<void>;
    }
    interface UNewsletterToggleSubscriptionButton {
        /**
          * @default ""
         */
        "componentClassName": string;
        "internalName": string;
        /**
          * @default ""
         */
        "subscribeClassName": string;
        /**
          * @default ""
         */
        "unsubscribeClassName": string;
    }
    interface UPaginationButton {
        /**
          * CSS classes to apply to the button element.
         */
        "componentClassName"?: string;
        /**
          * The direction of navigation.
          * @default "next"
         */
        "direction": "prev" | "next";
    }
    interface UPaginationPage {
        /**
          * CSS classes to apply to the span element.
         */
        "componentClassName"?: string;
    }
    interface UPasskey {
        /**
          * @default ""
         */
        "ariaDescribedBy"?: string;
        /**
          * @default ""
         */
        "componentClassName": string;
        /**
          * @default false
         */
        "disabled": boolean;
    }
    interface UPasswordField {
        /**
          * ARIA label for accessibility. Defaults based on the 'for' prop if not provided.
          * @default ""
         */
        "ariaLabel": string;
        /**
          * CSS classes to apply to the input element.
          * @default ""
         */
        "componentClassName": string;
        /**
          * The purpose of this password field: login, new-password, or password-confirmation.
          * @default "login"
         */
        "for": PasswordFieldFor;
    }
    interface UProfile {
        /**
          * Initial profile data as JSON string or object. If provided, skips fetching from API.
          * @default ""
         */
        "initialData": string | Record<string, string>;
        /**
          * Optional profile ID (for multi-profile scenarios).
         */
        "profileId"?: string;
        "submitProfile": () => Promise<void>;
    }
    interface URawField {
        /**
          * @default ""
         */
        "ariaDescribedBy": string;
        "attrName"?: string;
        "checked"?: boolean;
        "componentClassName"?: string;
        /**
          * @default "label"
         */
        "countryCodeDisplayOption"?: "icon" | "label";
        "disabled"?: boolean;
        /**
          * @default false
         */
        "emptyOption": boolean;
        "field": string;
        /**
          * @default "Please enter a valid phone number."
         */
        "invalidPhoneMessage": string;
        "multiSelectOptions"?: MultiSelectOption[];
        "options"?: string | Option[];
        "pattern"?: string;
        "patternErrorMessage"?: string;
        "placeholder"?: string;
        "radioOptions"?: RadioOption[];
        /**
          * @default ""
         */
        "readonlyPlaceholder": string;
        /**
          * @default false
         */
        "required": boolean;
        "specificPartKey"?: string;
        "tooltip"?: string;
        "type": string;
        "validationFunc"?: (value: string | string[]) => { valid: boolean; message?: string };
        "value"?: string | string[];
    }
    interface URegistrationButton {
        /**
          * @default ""
         */
        "componentClassName": string;
        "for": "email";
        /**
          * @default window.location.href
         */
        "redirectUri": string;
    }
    interface UResetPasswordButton {
        /**
          * CSS classes to apply to the button element.
          * @default ""
         */
        "componentClassName": string;
    }
    interface USendMagicCodeButton {
        /**
          * CSS classes to apply to the button element.
          * @default ""
         */
        "componentClassName": string;
        /**
          * If true, the button will be disabled.
          * @default false
         */
        "disabled": boolean;
    }
    interface USignedIn {
        /**
          * CSS classes to apply to the host element.
          * @default ""
         */
        "componentClassName": string;
        /**
          * If true, shows content when user is NOT signed in (inverts the condition).
          * @default false
         */
        "not": boolean;
    }
    interface USigninRoot {
        /**
          * CSS classes to apply to the host element.
          * @default ""
         */
        "componentClassName": string;
    }
    interface USigninStep {
        /**
          * If true, the step will always render regardless of the current authentication step.
          * @default false
         */
        "alwaysRender": boolean;
        "isActive": () => Promise<boolean>;
        /**
          * The name of this step in the sign-in flow.
         */
        "name": "email" | "verification" | "magic-code" | "reset-password" | "single-login" | "missing-fields" | "registration";
        "submit": () => Promise<void>;
    }
    interface USocialLoginButton {
        /**
          * If true, shows only the provider icon without text.
          * @default false
         */
        "iconOnly": boolean;
        /**
          * The OAuth provider (google, linkedin, apple, discord, facebook, or unidy).
          * @default "google"
         */
        "provider": SocialLoginProvider;
        /**
          * The URL to redirect to after authentication. Defaults to current page.
          * @default window.location.href
         */
        "redirectUri": string;
        /**
          * Button theme: 'light' (white background) or 'dark' (dark background).
          * @default "light"
         */
        "theme": "light" | "dark";
    }
    interface USpinner {
    }
    interface USubmitButton {
        /**
          * CSS classes to apply to the button element.
          * @default ""
         */
        "componentClassName": string;
        /**
          * If true, the button will be disabled.
          * @default false
         */
        "disabled": boolean;
        /**
          * The action type for the button. Varies by context (auth: email/password/magic-code/reset-password, newsletter: subscribe/login).
         */
        "for"?: AuthButtonFor | NewsletterButtonFor;
        /**
          * Custom button text. If not provided, uses context-specific defaults.
         */
        "text"?: string;
    }
    interface UTicketableExport {
        /**
          * CSS classes to apply to the button element.
         */
        "componentClassName"?: string;
        /**
          * Whether the export is available. Set to false to disable the button.
          * @default true
         */
        "exportable": boolean;
        /**
          * The export format (pdf or pkpass).
         */
        "format": ExportFormat;
    }
    interface UTicketableList {
        /**
          * CSS classes to apply to the container element.
         */
        "containerClass"?: string;
        /**
          * Filter string for API queries (e.g., 'state=active;payment_state=paid').
          * @default ""
         */
        "filter": string;
        /**
          * Number of items per page.
          * @default 10
         */
        "limit": number;
        /**
          * Current page number.
          * @default 1
         */
        "page": number;
        /**
          * Pagination metadata from the API response.
          * @default null
         */
        "paginationMeta": PaginationMeta | null;
        /**
          * If true, replaces all text content with skeleton loaders.
          * @default false
         */
        "skeletonAllText"?: boolean;
        /**
          * Number of skeleton items to show while loading. Defaults to limit.
         */
        "skeletonCount"?: number;
        /**
          * Pagination store instance for external state management.
          * @default null
         */
        "store": PaginationStore | null;
        /**
          * CSS selector for the target element where items will be rendered.
         */
        "target"?: string;
        /**
          * The type of ticketable items to list ('ticket' or 'subscription').
         */
        "ticketableType": "ticket" | "subscription";
    }
}
export interface UConfigCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUConfigElement;
}
export interface ULogoutButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLULogoutButtonElement;
}
export interface UNewsletterRootCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUNewsletterRootElement;
}
export interface UProfileCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUProfileElement;
}
export interface USigninRootCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUSigninRootElement;
}
export interface UTicketableExportCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUTicketableExportElement;
}
export interface UTicketableListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUTicketableListElement;
}
declare global {
    interface HTMLUBackButtonElement extends Components.UBackButton, HTMLStencilElement {
    }
    var HTMLUBackButtonElement: {
        prototype: HTMLUBackButtonElement;
        new (): HTMLUBackButtonElement;
    };
    interface HTMLUConditionalRenderElement extends Components.UConditionalRender, HTMLStencilElement {
    }
    var HTMLUConditionalRenderElement: {
        prototype: HTMLUConditionalRenderElement;
        new (): HTMLUConditionalRenderElement;
    };
    interface HTMLUConfigElementEventMap {
        "unidyInitialized": Config;
        "configChange": ConfigChange;
    }
    interface HTMLUConfigElement extends Components.UConfig, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUConfigElementEventMap>(type: K, listener: (this: HTMLUConfigElement, ev: UConfigCustomEvent<HTMLUConfigElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUConfigElementEventMap>(type: K, listener: (this: HTMLUConfigElement, ev: UConfigCustomEvent<HTMLUConfigElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUConfigElement: {
        prototype: HTMLUConfigElement;
        new (): HTMLUConfigElement;
    };
    interface HTMLUEmailFieldElement extends Components.UEmailField, HTMLStencilElement {
    }
    var HTMLUEmailFieldElement: {
        prototype: HTMLUEmailFieldElement;
        new (): HTMLUEmailFieldElement;
    };
    interface HTMLUErrorMessageElement extends Components.UErrorMessage, HTMLStencilElement {
    }
    var HTMLUErrorMessageElement: {
        prototype: HTMLUErrorMessageElement;
        new (): HTMLUErrorMessageElement;
    };
    interface HTMLUFieldElement extends Components.UField, HTMLStencilElement {
    }
    var HTMLUFieldElement: {
        prototype: HTMLUFieldElement;
        new (): HTMLUFieldElement;
    };
    interface HTMLUFlashMessageElement extends Components.UFlashMessage, HTMLStencilElement {
    }
    var HTMLUFlashMessageElement: {
        prototype: HTMLUFlashMessageElement;
        new (): HTMLUFlashMessageElement;
    };
    interface HTMLUFullProfileElement extends Components.UFullProfile, HTMLStencilElement {
    }
    var HTMLUFullProfileElement: {
        prototype: HTMLUFullProfileElement;
        new (): HTMLUFullProfileElement;
    };
    interface HTMLUJumpToServiceElement extends Components.UJumpToService, HTMLStencilElement {
    }
    var HTMLUJumpToServiceElement: {
        prototype: HTMLUJumpToServiceElement;
        new (): HTMLUJumpToServiceElement;
    };
    interface HTMLUJumpToUnidyElement extends Components.UJumpToUnidy, HTMLStencilElement {
    }
    var HTMLUJumpToUnidyElement: {
        prototype: HTMLUJumpToUnidyElement;
        new (): HTMLUJumpToUnidyElement;
    };
    interface HTMLULogoutButtonElementEventMap {
        "logout": void;
    }
    interface HTMLULogoutButtonElement extends Components.ULogoutButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLULogoutButtonElementEventMap>(type: K, listener: (this: HTMLULogoutButtonElement, ev: ULogoutButtonCustomEvent<HTMLULogoutButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLULogoutButtonElementEventMap>(type: K, listener: (this: HTMLULogoutButtonElement, ev: ULogoutButtonCustomEvent<HTMLULogoutButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLULogoutButtonElement: {
        prototype: HTMLULogoutButtonElement;
        new (): HTMLULogoutButtonElement;
    };
    interface HTMLUMagicCodeFieldElement extends Components.UMagicCodeField, HTMLStencilElement {
    }
    var HTMLUMagicCodeFieldElement: {
        prototype: HTMLUMagicCodeFieldElement;
        new (): HTMLUMagicCodeFieldElement;
    };
    interface HTMLUMissingFieldElement extends Components.UMissingField, HTMLStencilElement {
    }
    var HTMLUMissingFieldElement: {
        prototype: HTMLUMissingFieldElement;
        new (): HTMLUMissingFieldElement;
    };
    interface HTMLUMissingFieldsSubmitButtonElement extends Components.UMissingFieldsSubmitButton, HTMLStencilElement {
    }
    var HTMLUMissingFieldsSubmitButtonElement: {
        prototype: HTMLUMissingFieldsSubmitButtonElement;
        new (): HTMLUMissingFieldsSubmitButtonElement;
    };
    interface HTMLUNewsletterCheckboxElement extends Components.UNewsletterCheckbox, HTMLStencilElement {
    }
    var HTMLUNewsletterCheckboxElement: {
        prototype: HTMLUNewsletterCheckboxElement;
        new (): HTMLUNewsletterCheckboxElement;
    };
    interface HTMLUNewsletterConsentCheckboxElement extends Components.UNewsletterConsentCheckbox, HTMLStencilElement {
    }
    var HTMLUNewsletterConsentCheckboxElement: {
        prototype: HTMLUNewsletterConsentCheckboxElement;
        new (): HTMLUNewsletterConsentCheckboxElement;
    };
    interface HTMLUNewsletterLogoutButtonElement extends Components.UNewsletterLogoutButton, HTMLStencilElement {
    }
    var HTMLUNewsletterLogoutButtonElement: {
        prototype: HTMLUNewsletterLogoutButtonElement;
        new (): HTMLUNewsletterLogoutButtonElement;
    };
    interface HTMLUNewsletterPreferenceCheckboxElement extends Components.UNewsletterPreferenceCheckbox, HTMLStencilElement {
    }
    var HTMLUNewsletterPreferenceCheckboxElement: {
        prototype: HTMLUNewsletterPreferenceCheckboxElement;
        new (): HTMLUNewsletterPreferenceCheckboxElement;
    };
    interface HTMLUNewsletterResendDoiButtonElement extends Components.UNewsletterResendDoiButton, HTMLStencilElement {
    }
    var HTMLUNewsletterResendDoiButtonElement: {
        prototype: HTMLUNewsletterResendDoiButtonElement;
        new (): HTMLUNewsletterResendDoiButtonElement;
    };
    interface HTMLUNewsletterRootElementEventMap {
        "uNewsletterSuccess": { email: string; newsletters: string[] };
        "uNewsletterError": { email: string; error: string };
    }
    interface HTMLUNewsletterRootElement extends Components.UNewsletterRoot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUNewsletterRootElementEventMap>(type: K, listener: (this: HTMLUNewsletterRootElement, ev: UNewsletterRootCustomEvent<HTMLUNewsletterRootElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUNewsletterRootElementEventMap>(type: K, listener: (this: HTMLUNewsletterRootElement, ev: UNewsletterRootCustomEvent<HTMLUNewsletterRootElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUNewsletterRootElement: {
        prototype: HTMLUNewsletterRootElement;
        new (): HTMLUNewsletterRootElement;
    };
    interface HTMLUNewsletterToggleSubscriptionButtonElement extends Components.UNewsletterToggleSubscriptionButton, HTMLStencilElement {
    }
    var HTMLUNewsletterToggleSubscriptionButtonElement: {
        prototype: HTMLUNewsletterToggleSubscriptionButtonElement;
        new (): HTMLUNewsletterToggleSubscriptionButtonElement;
    };
    interface HTMLUPaginationButtonElement extends Components.UPaginationButton, HTMLStencilElement {
    }
    var HTMLUPaginationButtonElement: {
        prototype: HTMLUPaginationButtonElement;
        new (): HTMLUPaginationButtonElement;
    };
    interface HTMLUPaginationPageElement extends Components.UPaginationPage, HTMLStencilElement {
    }
    var HTMLUPaginationPageElement: {
        prototype: HTMLUPaginationPageElement;
        new (): HTMLUPaginationPageElement;
    };
    interface HTMLUPasskeyElement extends Components.UPasskey, HTMLStencilElement {
    }
    var HTMLUPasskeyElement: {
        prototype: HTMLUPasskeyElement;
        new (): HTMLUPasskeyElement;
    };
    interface HTMLUPasswordFieldElement extends Components.UPasswordField, HTMLStencilElement {
    }
    var HTMLUPasswordFieldElement: {
        prototype: HTMLUPasswordFieldElement;
        new (): HTMLUPasswordFieldElement;
    };
    interface HTMLUProfileElementEventMap {
        "uProfileSuccess": { message: string; payload: ProfileRaw };
        "uProfileError": {
    error: string;
    details: {
      fieldErrors?: Record<string, string>;
      httpStatus?: number;
      responseData?: unknown;
    };
  };
    }
    interface HTMLUProfileElement extends Components.UProfile, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUProfileElementEventMap>(type: K, listener: (this: HTMLUProfileElement, ev: UProfileCustomEvent<HTMLUProfileElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUProfileElementEventMap>(type: K, listener: (this: HTMLUProfileElement, ev: UProfileCustomEvent<HTMLUProfileElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUProfileElement: {
        prototype: HTMLUProfileElement;
        new (): HTMLUProfileElement;
    };
    interface HTMLURawFieldElement extends Components.URawField, HTMLStencilElement {
    }
    var HTMLURawFieldElement: {
        prototype: HTMLURawFieldElement;
        new (): HTMLURawFieldElement;
    };
    interface HTMLURegistrationButtonElement extends Components.URegistrationButton, HTMLStencilElement {
    }
    var HTMLURegistrationButtonElement: {
        prototype: HTMLURegistrationButtonElement;
        new (): HTMLURegistrationButtonElement;
    };
    interface HTMLUResetPasswordButtonElement extends Components.UResetPasswordButton, HTMLStencilElement {
    }
    var HTMLUResetPasswordButtonElement: {
        prototype: HTMLUResetPasswordButtonElement;
        new (): HTMLUResetPasswordButtonElement;
    };
    interface HTMLUSendMagicCodeButtonElement extends Components.USendMagicCodeButton, HTMLStencilElement {
    }
    var HTMLUSendMagicCodeButtonElement: {
        prototype: HTMLUSendMagicCodeButtonElement;
        new (): HTMLUSendMagicCodeButtonElement;
    };
    interface HTMLUSignedInElement extends Components.USignedIn, HTMLStencilElement {
    }
    var HTMLUSignedInElement: {
        prototype: HTMLUSignedInElement;
        new (): HTMLUSignedInElement;
    };
    interface HTMLUSigninRootElementEventMap {
        "authEvent": TokenResponse;
        "errorEvent": { error: string };
    }
    interface HTMLUSigninRootElement extends Components.USigninRoot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUSigninRootElementEventMap>(type: K, listener: (this: HTMLUSigninRootElement, ev: USigninRootCustomEvent<HTMLUSigninRootElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUSigninRootElementEventMap>(type: K, listener: (this: HTMLUSigninRootElement, ev: USigninRootCustomEvent<HTMLUSigninRootElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUSigninRootElement: {
        prototype: HTMLUSigninRootElement;
        new (): HTMLUSigninRootElement;
    };
    interface HTMLUSigninStepElement extends Components.USigninStep, HTMLStencilElement {
    }
    var HTMLUSigninStepElement: {
        prototype: HTMLUSigninStepElement;
        new (): HTMLUSigninStepElement;
    };
    interface HTMLUSocialLoginButtonElement extends Components.USocialLoginButton, HTMLStencilElement {
    }
    var HTMLUSocialLoginButtonElement: {
        prototype: HTMLUSocialLoginButtonElement;
        new (): HTMLUSocialLoginButtonElement;
    };
    interface HTMLUSpinnerElement extends Components.USpinner, HTMLStencilElement {
    }
    var HTMLUSpinnerElement: {
        prototype: HTMLUSpinnerElement;
        new (): HTMLUSpinnerElement;
    };
    interface HTMLUSubmitButtonElement extends Components.USubmitButton, HTMLStencilElement {
    }
    var HTMLUSubmitButtonElement: {
        prototype: HTMLUSubmitButtonElement;
        new (): HTMLUSubmitButtonElement;
    };
    interface HTMLUTicketableExportElementEventMap {
        "uTicketableExportSuccess": { url: string; format: ExportFormat };
        "uTicketableExportError": { error: string };
    }
    interface HTMLUTicketableExportElement extends Components.UTicketableExport, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUTicketableExportElementEventMap>(type: K, listener: (this: HTMLUTicketableExportElement, ev: UTicketableExportCustomEvent<HTMLUTicketableExportElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUTicketableExportElementEventMap>(type: K, listener: (this: HTMLUTicketableExportElement, ev: UTicketableExportCustomEvent<HTMLUTicketableExportElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUTicketableExportElement: {
        prototype: HTMLUTicketableExportElement;
        new (): HTMLUTicketableExportElement;
    };
    interface HTMLUTicketableListElementEventMap {
        "uTicketableListSuccess": {
    ticketableType: "ticket" | "subscription";
    items: Subscription[] | Ticket[];
    paginationMeta: PaginationMeta | null;
  };
        "uTicketableListError": {
    ticketableType?: "ticket" | "subscription";
    error: string;
  };
    }
    interface HTMLUTicketableListElement extends Components.UTicketableList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUTicketableListElementEventMap>(type: K, listener: (this: HTMLUTicketableListElement, ev: UTicketableListCustomEvent<HTMLUTicketableListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUTicketableListElementEventMap>(type: K, listener: (this: HTMLUTicketableListElement, ev: UTicketableListCustomEvent<HTMLUTicketableListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUTicketableListElement: {
        prototype: HTMLUTicketableListElement;
        new (): HTMLUTicketableListElement;
    };
    interface HTMLElementTagNameMap {
        "u-back-button": HTMLUBackButtonElement;
        "u-conditional-render": HTMLUConditionalRenderElement;
        "u-config": HTMLUConfigElement;
        "u-email-field": HTMLUEmailFieldElement;
        "u-error-message": HTMLUErrorMessageElement;
        "u-field": HTMLUFieldElement;
        "u-flash-message": HTMLUFlashMessageElement;
        "u-full-profile": HTMLUFullProfileElement;
        "u-jump-to-service": HTMLUJumpToServiceElement;
        "u-jump-to-unidy": HTMLUJumpToUnidyElement;
        "u-logout-button": HTMLULogoutButtonElement;
        "u-magic-code-field": HTMLUMagicCodeFieldElement;
        "u-missing-field": HTMLUMissingFieldElement;
        "u-missing-fields-submit-button": HTMLUMissingFieldsSubmitButtonElement;
        "u-newsletter-checkbox": HTMLUNewsletterCheckboxElement;
        "u-newsletter-consent-checkbox": HTMLUNewsletterConsentCheckboxElement;
        "u-newsletter-logout-button": HTMLUNewsletterLogoutButtonElement;
        "u-newsletter-preference-checkbox": HTMLUNewsletterPreferenceCheckboxElement;
        "u-newsletter-resend-doi-button": HTMLUNewsletterResendDoiButtonElement;
        "u-newsletter-root": HTMLUNewsletterRootElement;
        "u-newsletter-toggle-subscription-button": HTMLUNewsletterToggleSubscriptionButtonElement;
        "u-pagination-button": HTMLUPaginationButtonElement;
        "u-pagination-page": HTMLUPaginationPageElement;
        "u-passkey": HTMLUPasskeyElement;
        "u-password-field": HTMLUPasswordFieldElement;
        "u-profile": HTMLUProfileElement;
        "u-raw-field": HTMLURawFieldElement;
        "u-registration-button": HTMLURegistrationButtonElement;
        "u-reset-password-button": HTMLUResetPasswordButtonElement;
        "u-send-magic-code-button": HTMLUSendMagicCodeButtonElement;
        "u-signed-in": HTMLUSignedInElement;
        "u-signin-root": HTMLUSigninRootElement;
        "u-signin-step": HTMLUSigninStepElement;
        "u-social-login-button": HTMLUSocialLoginButtonElement;
        "u-spinner": HTMLUSpinnerElement;
        "u-submit-button": HTMLUSubmitButtonElement;
        "u-ticketable-export": HTMLUTicketableExportElement;
        "u-ticketable-list": HTMLUTicketableListElement;
    }
}
declare namespace LocalJSX {
    interface UBackButton {
        /**
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * If true, restarts the entire flow instead of going back one step. Use this for "Start over" buttons.
          * @default false
         */
        "restart"?: boolean;
    }
    interface UConditionalRender {
        "conditionFunction"?: (state: AuthState) => boolean;
        "is"?: string;
        /**
          * @default false
         */
        "not"?: boolean;
        "when"?: string;
    }
    interface UConfig {
        /**
          * Your Unidy API key.
          * @default ""
         */
        "apiKey"?: string;
        /**
          * The Unidy API base URL (e.g., 'https://your-tenant.unidy.io').
          * @default ""
         */
        "baseUrl"?: string;
        /**
          * If true, checks for existing session on load and restores authentication state.
          * @default false
         */
        "checkSignedIn"?: boolean;
        /**
          * Custom translations as JSON string or object. Keyed by locale code.
          * @default ""
         */
        "customTranslations"?: string | Record<string, TranslationTree>;
        /**
          * Fallback locale when translation is missing.
          * @default "en"
         */
        "fallbackLocale"?: string;
        /**
          * Current locale for translations (e.g., 'en', 'de', 'fr').
          * @default "en"
         */
        "locale"?: string;
        /**
          * SDK mode: 'production' or 'development'. Development mode enables verbose logging.
          * @default "production"
         */
        "mode"?: "production" | "development";
        /**
          * Fired when a configuration property changes.
         */
        "onConfigChange"?: (event: UConfigCustomEvent<ConfigChange>) => void;
        /**
          * Fired when SDK initialization is complete. Contains configuration details.
         */
        "onUnidyInitialized"?: (event: UConfigCustomEvent<Config>) => void;
    }
    interface UEmailField {
        /**
          * ARIA label for accessibility.
          * @default "Email"
         */
        "ariaLabel"?: string;
        /**
          * CSS classes to apply to the input element.
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * If true, the input will be disabled.
          * @default false
         */
        "disabled"?: boolean;
    }
    interface UErrorMessage {
        /**
          * CSS classes to apply to the host element.
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * Custom error messages keyed by error code. Overrides default translations.
         */
        "errorMessages"?: Record<string, string>;
        /**
          * The error type to display (e.g., 'email', 'password', 'general', 'connection').
         */
        "for": string;
    }
    interface UField {
        /**
          * CSS classes to apply to the input element.
         */
        "componentClassName"?: string;
        /**
          * For phone fields: how to display country code selector ('icon' or 'label').
          * @default "label"
         */
        "countryCodeDisplayOption"?: "icon" | "label";
        /**
          * If true, includes an empty option in select dropdowns.
          * @default true
         */
        "emptyOption"?: boolean;
        /**
          * The field name (e.g., 'first_name', 'custom_attributes.favorite_color').
         */
        "field": string;
        /**
          * Error message shown when phone number validation fails.
          * @default "Please enter a valid phone number."
         */
        "invalidPhoneMessage"?: string;
        /**
          * Regex pattern for custom validation.
         */
        "pattern"?: string;
        /**
          * Error message shown when pattern validation fails.
         */
        "patternErrorMessage"?: string;
        /**
          * Placeholder text for the input field.
         */
        "placeholder"?: string;
        /**
          * Placeholder text shown when field is readonly and has no value.
          * @default "No information"
         */
        "readonlyPlaceholder"?: string;
        /**
          * If true, renders the default label above the field.
          * @default true
         */
        "renderDefaultLabel"?: boolean;
        /**
          * If true, marks the field as required (in addition to backend configuration).
          * @default false
         */
        "required"?: boolean;
        /**
          * Custom validation function. Returns { valid: boolean, message?: string }.
         */
        "validationFunc"?: (value: string | string[]) => { valid: boolean; message?: string };
    }
    interface UFlashMessage {
        /**
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * @default null
         */
        "removeAfterSeconds"?: number | null;
    }
    interface UFullProfile {
        /**
          * For phone fields: how to display country code selector ('icon' or 'label').
          * @default "label"
         */
        "countryCodeDisplayOption"?: "icon" | "label";
        /**
          * Comma-separated list of field names to display. If not provided, shows all fields.
         */
        "fields"?: string;
    }
    interface UJumpToService {
        /**
          * Custom CSS class name(s) to apply to the button element.
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * If true, opens the URL in a new tab. Defaults to false.
          * @default false
         */
        "newtab"?: boolean;
        /**
          * Optional redirect URI for the OAuth flow. Must match one of the application's allowed redirect URIs.
         */
        "redirectUri"?: string;
        /**
          * Comma-separated list of OAuth scopes to request. Defaults to ["openid"] if not provided.
          * @example "openid,profile"
         */
        "scopes"?: string;
        /**
          * The OAuth Application ID (service ID) to jump to.
          * @example "2"
         */
        "serviceId": string;
        /**
          * If true, skips the OAuth authorization step (if already authorized once). Defaults to false.
          * @default false
         */
        "skipOauthAuthorization"?: boolean;
    }
    interface UJumpToUnidy {
        /**
          * Custom CSS class name(s) to apply to the button element.
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * If true, opens the URL in a new tab. Defaults to false.
          * @default false
         */
        "newtab"?: boolean;
        /**
          * If true, skips authentication and redirects directly to the Unidy path. Useful for public pages like terms of service.
          * @default false
         */
        "noAuth"?: boolean;
        /**
          * The Unidy path to redirect to. Must start with "/".
          * @example "/subscriptions"
          * @example "/tickets"
         */
        "path": string;
    }
    interface ULogoutButton {
        /**
          * CSS classes to apply to the button element.
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * Fired after successful logout.
         */
        "onLogout"?: (event: ULogoutButtonCustomEvent<void>) => void;
        /**
          * If true, reloads the page after successful logout.
          * @default true
         */
        "reloadOnSuccess"?: boolean;
    }
    interface UMagicCodeField {
        /**
          * CSS classes to apply to the container element.
          * @default ""
         */
        "componentClassName"?: string;
    }
    interface UMissingField {
        "componentClassName"?: string;
    }
    interface UMissingFieldsSubmitButton {
        /**
          * @default ""
         */
        "componentClassName"?: string;
    }
    interface UNewsletterCheckbox {
        /**
          * If true, the checkbox will be checked by default.
          * @default false
         */
        "checked"?: boolean;
        /**
          * CSS classes to apply to the checkbox element.
         */
        "componentClassName"?: string;
        /**
          * The internal name of the newsletter (as configured in the backend).
         */
        "internalName": string;
    }
    interface UNewsletterConsentCheckbox {
        /**
          * CSS classes to apply to the checkbox element.
         */
        "componentClassName"?: string;
    }
    interface UNewsletterLogoutButton {
        /**
          * @default ""
         */
        "componentClassName"?: string;
    }
    interface UNewsletterPreferenceCheckbox {
        /**
          * If true, the checkbox will be checked by default.
          * @default false
         */
        "checked"?: boolean;
        /**
          * CSS classes to apply to the checkbox element.
         */
        "componentClassName"?: string;
        /**
          * The internal name of the parent newsletter.
         */
        "internalName": string;
        /**
          * The preference identifier (e.g., 'daily', 'weekly', 'promotions').
         */
        "preferenceIdentifier": string;
    }
    interface UNewsletterResendDoiButton {
        /**
          * @default ""
         */
        "componentClassName"?: string;
        "internalName": string;
    }
    interface UNewsletterRoot {
        /**
          * CSS classes to apply to the host element.
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * Fired on newsletter subscription failure. Contains the email and error code.
         */
        "onUNewsletterError"?: (event: UNewsletterRootCustomEvent<{ email: string; error: string }>) => void;
        /**
          * Fired on successful newsletter subscription. Contains the email and subscribed newsletters.
         */
        "onUNewsletterSuccess"?: (event: UNewsletterRootCustomEvent<{ email: string; newsletters: string[] }>) => void;
    }
    interface UNewsletterToggleSubscriptionButton {
        /**
          * @default ""
         */
        "componentClassName"?: string;
        "internalName": string;
        /**
          * @default ""
         */
        "subscribeClassName"?: string;
        /**
          * @default ""
         */
        "unsubscribeClassName"?: string;
    }
    interface UPaginationButton {
        /**
          * CSS classes to apply to the button element.
         */
        "componentClassName"?: string;
        /**
          * The direction of navigation.
          * @default "next"
         */
        "direction"?: "prev" | "next";
    }
    interface UPaginationPage {
        /**
          * CSS classes to apply to the span element.
         */
        "componentClassName"?: string;
    }
    interface UPasskey {
        /**
          * @default ""
         */
        "ariaDescribedBy"?: string;
        /**
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
    }
    interface UPasswordField {
        /**
          * ARIA label for accessibility. Defaults based on the 'for' prop if not provided.
          * @default ""
         */
        "ariaLabel"?: string;
        /**
          * CSS classes to apply to the input element.
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * The purpose of this password field: login, new-password, or password-confirmation.
          * @default "login"
         */
        "for"?: PasswordFieldFor;
    }
    interface UProfile {
        /**
          * Initial profile data as JSON string or object. If provided, skips fetching from API.
          * @default ""
         */
        "initialData"?: string | Record<string, string>;
        /**
          * Fired on profile update failure. Contains error code and details including field errors.
         */
        "onUProfileError"?: (event: UProfileCustomEvent<{
    error: string;
    details: {
      fieldErrors?: Record<string, string>;
      httpStatus?: number;
      responseData?: unknown;
    };
  }>) => void;
        /**
          * Fired on successful profile update. Contains success message and updated profile data.
         */
        "onUProfileSuccess"?: (event: UProfileCustomEvent<{ message: string; payload: ProfileRaw }>) => void;
        /**
          * Optional profile ID (for multi-profile scenarios).
         */
        "profileId"?: string;
    }
    interface URawField {
        /**
          * @default ""
         */
        "ariaDescribedBy"?: string;
        "attrName"?: string;
        "checked"?: boolean;
        "componentClassName"?: string;
        /**
          * @default "label"
         */
        "countryCodeDisplayOption"?: "icon" | "label";
        "disabled"?: boolean;
        /**
          * @default false
         */
        "emptyOption"?: boolean;
        "field": string;
        /**
          * @default "Please enter a valid phone number."
         */
        "invalidPhoneMessage"?: string;
        "multiSelectOptions"?: MultiSelectOption[];
        "options"?: string | Option[];
        "pattern"?: string;
        "patternErrorMessage"?: string;
        "placeholder"?: string;
        "radioOptions"?: RadioOption[];
        /**
          * @default ""
         */
        "readonlyPlaceholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        "specificPartKey"?: string;
        "tooltip"?: string;
        "type": string;
        "validationFunc"?: (value: string | string[]) => { valid: boolean; message?: string };
        "value"?: string | string[];
    }
    interface URegistrationButton {
        /**
          * @default ""
         */
        "componentClassName"?: string;
        "for": "email";
        /**
          * @default window.location.href
         */
        "redirectUri"?: string;
    }
    interface UResetPasswordButton {
        /**
          * CSS classes to apply to the button element.
          * @default ""
         */
        "componentClassName"?: string;
    }
    interface USendMagicCodeButton {
        /**
          * CSS classes to apply to the button element.
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * If true, the button will be disabled.
          * @default false
         */
        "disabled"?: boolean;
    }
    interface USignedIn {
        /**
          * CSS classes to apply to the host element.
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * If true, shows content when user is NOT signed in (inverts the condition).
          * @default false
         */
        "not"?: boolean;
    }
    interface USigninRoot {
        /**
          * CSS classes to apply to the host element.
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * Fired on successful authentication. Contains the JWT and refresh token.
         */
        "onAuthEvent"?: (event: USigninRootCustomEvent<TokenResponse>) => void;
        /**
          * Fired on authentication failure. Contains the error code.
         */
        "onErrorEvent"?: (event: USigninRootCustomEvent<{ error: string }>) => void;
    }
    interface USigninStep {
        /**
          * If true, the step will always render regardless of the current authentication step.
          * @default false
         */
        "alwaysRender"?: boolean;
        /**
          * The name of this step in the sign-in flow.
         */
        "name": "email" | "verification" | "magic-code" | "reset-password" | "single-login" | "missing-fields" | "registration";
    }
    interface USocialLoginButton {
        /**
          * If true, shows only the provider icon without text.
          * @default false
         */
        "iconOnly"?: boolean;
        /**
          * The OAuth provider (google, linkedin, apple, discord, facebook, or unidy).
          * @default "google"
         */
        "provider"?: SocialLoginProvider;
        /**
          * The URL to redirect to after authentication. Defaults to current page.
          * @default window.location.href
         */
        "redirectUri"?: string;
        /**
          * Button theme: 'light' (white background) or 'dark' (dark background).
          * @default "light"
         */
        "theme"?: "light" | "dark";
    }
    interface USpinner {
    }
    interface USubmitButton {
        /**
          * CSS classes to apply to the button element.
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * If true, the button will be disabled.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The action type for the button. Varies by context (auth: email/password/magic-code/reset-password, newsletter: subscribe/login).
         */
        "for"?: AuthButtonFor | NewsletterButtonFor;
        /**
          * Custom button text. If not provided, uses context-specific defaults.
         */
        "text"?: string;
    }
    interface UTicketableExport {
        /**
          * CSS classes to apply to the button element.
         */
        "componentClassName"?: string;
        /**
          * Whether the export is available. Set to false to disable the button.
          * @default true
         */
        "exportable"?: boolean;
        /**
          * The export format (pdf or pkpass).
         */
        "format": ExportFormat;
        "onUTicketableExportError"?: (event: UTicketableExportCustomEvent<{ error: string }>) => void;
        "onUTicketableExportSuccess"?: (event: UTicketableExportCustomEvent<{ url: string; format: ExportFormat }>) => void;
    }
    interface UTicketableList {
        /**
          * CSS classes to apply to the container element.
         */
        "containerClass"?: string;
        /**
          * Filter string for API queries (e.g., 'state=active;payment_state=paid').
          * @default ""
         */
        "filter"?: string;
        /**
          * Number of items per page.
          * @default 10
         */
        "limit"?: number;
        /**
          * Fired when fetching items fails. Contains the error message.
         */
        "onUTicketableListError"?: (event: UTicketableListCustomEvent<{
    ticketableType?: "ticket" | "subscription";
    error: string;
  }>) => void;
        /**
          * Fired when items are successfully fetched. Contains items and pagination metadata.
         */
        "onUTicketableListSuccess"?: (event: UTicketableListCustomEvent<{
    ticketableType: "ticket" | "subscription";
    items: Subscription[] | Ticket[];
    paginationMeta: PaginationMeta | null;
  }>) => void;
        /**
          * Current page number.
          * @default 1
         */
        "page"?: number;
        /**
          * Pagination metadata from the API response.
          * @default null
         */
        "paginationMeta"?: PaginationMeta | null;
        /**
          * If true, replaces all text content with skeleton loaders.
          * @default false
         */
        "skeletonAllText"?: boolean;
        /**
          * Number of skeleton items to show while loading. Defaults to limit.
         */
        "skeletonCount"?: number;
        /**
          * Pagination store instance for external state management.
          * @default null
         */
        "store"?: PaginationStore | null;
        /**
          * CSS selector for the target element where items will be rendered.
         */
        "target"?: string;
        /**
          * The type of ticketable items to list ('ticket' or 'subscription').
         */
        "ticketableType": "ticket" | "subscription";
    }
    interface IntrinsicElements {
        "u-back-button": UBackButton;
        "u-conditional-render": UConditionalRender;
        "u-config": UConfig;
        "u-email-field": UEmailField;
        "u-error-message": UErrorMessage;
        "u-field": UField;
        "u-flash-message": UFlashMessage;
        "u-full-profile": UFullProfile;
        "u-jump-to-service": UJumpToService;
        "u-jump-to-unidy": UJumpToUnidy;
        "u-logout-button": ULogoutButton;
        "u-magic-code-field": UMagicCodeField;
        "u-missing-field": UMissingField;
        "u-missing-fields-submit-button": UMissingFieldsSubmitButton;
        "u-newsletter-checkbox": UNewsletterCheckbox;
        "u-newsletter-consent-checkbox": UNewsletterConsentCheckbox;
        "u-newsletter-logout-button": UNewsletterLogoutButton;
        "u-newsletter-preference-checkbox": UNewsletterPreferenceCheckbox;
        "u-newsletter-resend-doi-button": UNewsletterResendDoiButton;
        "u-newsletter-root": UNewsletterRoot;
        "u-newsletter-toggle-subscription-button": UNewsletterToggleSubscriptionButton;
        "u-pagination-button": UPaginationButton;
        "u-pagination-page": UPaginationPage;
        "u-passkey": UPasskey;
        "u-password-field": UPasswordField;
        "u-profile": UProfile;
        "u-raw-field": URawField;
        "u-registration-button": URegistrationButton;
        "u-reset-password-button": UResetPasswordButton;
        "u-send-magic-code-button": USendMagicCodeButton;
        "u-signed-in": USignedIn;
        "u-signin-root": USigninRoot;
        "u-signin-step": USigninStep;
        "u-social-login-button": USocialLoginButton;
        "u-spinner": USpinner;
        "u-submit-button": USubmitButton;
        "u-ticketable-export": UTicketableExport;
        "u-ticketable-list": UTicketableList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "u-back-button": LocalJSX.UBackButton & JSXBase.HTMLAttributes<HTMLUBackButtonElement>;
            "u-conditional-render": LocalJSX.UConditionalRender & JSXBase.HTMLAttributes<HTMLUConditionalRenderElement>;
            "u-config": LocalJSX.UConfig & JSXBase.HTMLAttributes<HTMLUConfigElement>;
            "u-email-field": LocalJSX.UEmailField & JSXBase.HTMLAttributes<HTMLUEmailFieldElement>;
            "u-error-message": LocalJSX.UErrorMessage & JSXBase.HTMLAttributes<HTMLUErrorMessageElement>;
            "u-field": LocalJSX.UField & JSXBase.HTMLAttributes<HTMLUFieldElement>;
            "u-flash-message": LocalJSX.UFlashMessage & JSXBase.HTMLAttributes<HTMLUFlashMessageElement>;
            "u-full-profile": LocalJSX.UFullProfile & JSXBase.HTMLAttributes<HTMLUFullProfileElement>;
            "u-jump-to-service": LocalJSX.UJumpToService & JSXBase.HTMLAttributes<HTMLUJumpToServiceElement>;
            "u-jump-to-unidy": LocalJSX.UJumpToUnidy & JSXBase.HTMLAttributes<HTMLUJumpToUnidyElement>;
            "u-logout-button": LocalJSX.ULogoutButton & JSXBase.HTMLAttributes<HTMLULogoutButtonElement>;
            "u-magic-code-field": LocalJSX.UMagicCodeField & JSXBase.HTMLAttributes<HTMLUMagicCodeFieldElement>;
            "u-missing-field": LocalJSX.UMissingField & JSXBase.HTMLAttributes<HTMLUMissingFieldElement>;
            "u-missing-fields-submit-button": LocalJSX.UMissingFieldsSubmitButton & JSXBase.HTMLAttributes<HTMLUMissingFieldsSubmitButtonElement>;
            "u-newsletter-checkbox": LocalJSX.UNewsletterCheckbox & JSXBase.HTMLAttributes<HTMLUNewsletterCheckboxElement>;
            "u-newsletter-consent-checkbox": LocalJSX.UNewsletterConsentCheckbox & JSXBase.HTMLAttributes<HTMLUNewsletterConsentCheckboxElement>;
            "u-newsletter-logout-button": LocalJSX.UNewsletterLogoutButton & JSXBase.HTMLAttributes<HTMLUNewsletterLogoutButtonElement>;
            "u-newsletter-preference-checkbox": LocalJSX.UNewsletterPreferenceCheckbox & JSXBase.HTMLAttributes<HTMLUNewsletterPreferenceCheckboxElement>;
            "u-newsletter-resend-doi-button": LocalJSX.UNewsletterResendDoiButton & JSXBase.HTMLAttributes<HTMLUNewsletterResendDoiButtonElement>;
            "u-newsletter-root": LocalJSX.UNewsletterRoot & JSXBase.HTMLAttributes<HTMLUNewsletterRootElement>;
            "u-newsletter-toggle-subscription-button": LocalJSX.UNewsletterToggleSubscriptionButton & JSXBase.HTMLAttributes<HTMLUNewsletterToggleSubscriptionButtonElement>;
            "u-pagination-button": LocalJSX.UPaginationButton & JSXBase.HTMLAttributes<HTMLUPaginationButtonElement>;
            "u-pagination-page": LocalJSX.UPaginationPage & JSXBase.HTMLAttributes<HTMLUPaginationPageElement>;
            "u-passkey": LocalJSX.UPasskey & JSXBase.HTMLAttributes<HTMLUPasskeyElement>;
            "u-password-field": LocalJSX.UPasswordField & JSXBase.HTMLAttributes<HTMLUPasswordFieldElement>;
            "u-profile": LocalJSX.UProfile & JSXBase.HTMLAttributes<HTMLUProfileElement>;
            "u-raw-field": LocalJSX.URawField & JSXBase.HTMLAttributes<HTMLURawFieldElement>;
            "u-registration-button": LocalJSX.URegistrationButton & JSXBase.HTMLAttributes<HTMLURegistrationButtonElement>;
            "u-reset-password-button": LocalJSX.UResetPasswordButton & JSXBase.HTMLAttributes<HTMLUResetPasswordButtonElement>;
            "u-send-magic-code-button": LocalJSX.USendMagicCodeButton & JSXBase.HTMLAttributes<HTMLUSendMagicCodeButtonElement>;
            "u-signed-in": LocalJSX.USignedIn & JSXBase.HTMLAttributes<HTMLUSignedInElement>;
            "u-signin-root": LocalJSX.USigninRoot & JSXBase.HTMLAttributes<HTMLUSigninRootElement>;
            "u-signin-step": LocalJSX.USigninStep & JSXBase.HTMLAttributes<HTMLUSigninStepElement>;
            "u-social-login-button": LocalJSX.USocialLoginButton & JSXBase.HTMLAttributes<HTMLUSocialLoginButtonElement>;
            "u-spinner": LocalJSX.USpinner & JSXBase.HTMLAttributes<HTMLUSpinnerElement>;
            "u-submit-button": LocalJSX.USubmitButton & JSXBase.HTMLAttributes<HTMLUSubmitButtonElement>;
            "u-ticketable-export": LocalJSX.UTicketableExport & JSXBase.HTMLAttributes<HTMLUTicketableExportElement>;
            "u-ticketable-list": LocalJSX.UTicketableList & JSXBase.HTMLAttributes<HTMLUTicketableListElement>;
        }
    }
}
