/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AuthState } from "./auth/store/auth-store";
import { Config, ConfigChange } from "./shared/components/config/config";
import { PasswordFieldFor } from "./auth/components/password-field/password-field";
import { Option } from "./profile/components/raw-input-fields/Select";
import { RadioOption } from "./profile/components/raw-input-fields/RadioGroup";
import { MultiSelectOption } from "./profile/components/raw-input-fields/MultiSelect";
import { TokenResponse } from "./auth/api/auth";
import { AuthButtonFor } from "./auth/components/signin-step/signin-step";
import { AuthButtonFor as AuthButtonFor1 } from "./shared/components/submit-button/submit-button";
import { PaginationMeta } from "./api";
import { PaginationStore } from "./ticketable/store/pagination-store";
export { AuthState } from "./auth/store/auth-store";
export { Config, ConfigChange } from "./shared/components/config/config";
export { PasswordFieldFor } from "./auth/components/password-field/password-field";
export { Option } from "./profile/components/raw-input-fields/Select";
export { RadioOption } from "./profile/components/raw-input-fields/RadioGroup";
export { MultiSelectOption } from "./profile/components/raw-input-fields/MultiSelect";
export { TokenResponse } from "./auth/api/auth";
export { AuthButtonFor } from "./auth/components/signin-step/signin-step";
export { AuthButtonFor as AuthButtonFor1 } from "./shared/components/submit-button/submit-button";
export { PaginationMeta } from "./api";
export { PaginationStore } from "./ticketable/store/pagination-store";
export namespace Components {
    interface NewsletterCheckbox {
        "checked": boolean;
        "componentClassName"?: string;
        "internalName": string;
        "label": string;
    }
    interface UConditionalRender {
        "conditionFunction"?: (state: AuthState) => boolean;
        "is"?: string;
        /**
          * @default false
         */
        "not": boolean;
        "when"?: string;
    }
    interface UConfig {
        /**
          * @default ""
         */
        "apiKey": string;
        /**
          * @default ""
         */
        "baseUrl": string;
        /**
          * @default ""
         */
        "customTranslations": string | Record<string, TranslationTree>;
        /**
          * @default "en"
         */
        "fallbackLocale": string;
        /**
          * @default "en"
         */
        "locale": string;
        /**
          * @default "production"
         */
        "mode": "production" | "development";
    }
    interface UEmailField {
        /**
          * @default "Email"
         */
        "ariaLabel": string;
        /**
          * @default ""
         */
        "componentClassName": string;
        /**
          * @default false
         */
        "disabled": boolean;
        "placeholder"?: string;
    }
    interface UErrorMessage {
        /**
          * @default ""
         */
        "componentClassName": string;
        "errorMessages"?: Record<string, string>;
        "for": "email" | "password" | "magicCode" | "resetPassword" | "general" | "connection";
    }
    interface UField {
        "componentClassName"?: string;
        /**
          * @default "label"
         */
        "countryCodeDisplayOption"?: "icon" | "label";
        /**
          * @default true
         */
        "emptyOption": boolean;
        "field": string;
        /**
          * @default "Please enter a valid phone number."
         */
        "invalidPhoneMessage": string;
        "pattern"?: string;
        "patternErrorMessage"?: string;
        "placeholder"?: string;
        /**
          * @default "No information"
         */
        "readonlyPlaceholder": string;
        /**
          * @default true
         */
        "renderDefaultLabel": boolean;
        /**
          * @default false
         */
        "required": boolean;
        "validationFunc"?: (value: string | string[]) => { valid: boolean; message?: string };
    }
    interface UFlashMessage {
        /**
          * @default ""
         */
        "componentClassName": string;
        /**
          * @default null
         */
        "removeAfterSeconds": number | null;
    }
    interface UFullProfile {
        /**
          * @default "label"
         */
        "countryCodeDisplayOption"?: "icon" | "label";
        "fields"?: string;
        /**
          * @default ""
         */
        "submitButtonText"?: string;
    }
    interface ULogoutButton {
        /**
          * @default ""
         */
        "componentClassName": string;
        /**
          * @default true
         */
        "reloadOnSuccess": boolean;
    }
    interface UMagicCodeField {
        /**
          * @default ""
         */
        "componentClassName": string;
    }
    interface UMissingField {
    }
    interface UMissingFieldsSubmitButton {
    }
    interface UNewsletterRoot {
        /**
          * @default ""
         */
        "componentClassName": string;
        "isLoading": () => Promise<boolean>;
        "isSubmitDisabled": () => Promise<boolean>;
        "submit": () => Promise<void>;
    }
    interface UPaginationButton {
        "customClass"?: string;
        /**
          * @default "next"
         */
        "direction": "prev" | "next";
    }
    interface UPaginationPage {
        "customClass"?: string;
    }
    interface UPasskey {
        /**
          * @default ""
         */
        "ariaDescribedBy"?: string;
        /**
          * @default ""
         */
        "componentClassName": string;
        /**
          * @default false
         */
        "disabled": boolean;
    }
    interface UPasswordField {
        /**
          * @default ""
         */
        "ariaLabel": string;
        /**
          * @default ""
         */
        "componentClassName": string;
        /**
          * @default "login"
         */
        "for": PasswordFieldFor;
        /**
          * @default null
         */
        "placeholder": any;
    }
    interface UProfile {
        /**
          * @default ""
         */
        "initialData": string | Record<string, string>;
        "isLoading": () => Promise<boolean>;
        "isSubmitDisabled": () => Promise<boolean>;
        "profileId"?: string;
        "submit": () => Promise<void>;
    }
    interface URawField {
        /**
          * @default ""
         */
        "ariaDescribedBy": string;
        "attrName"?: string;
        "checked"?: boolean;
        "componentClassName"?: string;
        /**
          * @default "label"
         */
        "countryCodeDisplayOption"?: "icon" | "label";
        "disabled"?: boolean;
        /**
          * @default false
         */
        "emptyOption": boolean;
        "field": string;
        /**
          * @default "Please enter a valid phone number."
         */
        "invalidPhoneMessage": string;
        "multiSelectOptions"?: MultiSelectOption[];
        "options"?: string | Option[];
        "pattern"?: string;
        "patternErrorMessage"?: string;
        "placeholder"?: string;
        "radioOptions"?: RadioOption[];
        /**
          * @default ""
         */
        "readonlyPlaceholder": string;
        /**
          * @default false
         */
        "required": boolean;
        "specificPartKey"?: string;
        "tooltip"?: string;
        "type": string;
        "validationFunc"?: (value: string | string[]) => { valid: boolean; message?: string };
        "value"?: string | string[];
    }
    interface URegistrationButton {
        /**
          * @default ""
         */
        "componentClassName": string;
        "for": "email";
        /**
          * @default window.location.href
         */
        "redirectUri": string;
    }
    interface UResetPasswordButton {
        /**
          * @default ""
         */
        "componentClassName": string;
    }
    interface USendMagicCodeButton {
        /**
          * @default ""
         */
        "componentClassName": string;
        /**
          * @default false
         */
        "disabled": boolean;
    }
    interface USignedIn {
        /**
          * @default ""
         */
        "componentClassName": string;
    }
    interface USigninRoot {
        /**
          * @default ""
         */
        "componentClassName": string;
    }
    interface USigninStep {
        /**
          * @default false
         */
        "alwaysRender": boolean;
        "isActive": () => Promise<boolean>;
        "isLoading": () => Promise<boolean>;
        "isSubmitDisabled": (forProp?: AuthButtonFor) => Promise<boolean>;
        "name": "email" | "verification" | "reset-password" | "registration";
        "submit": () => Promise<void>;
    }
    interface USigninStrategy {
        /**
          * @default ""
         */
        "componentClassName": string;
        "type": "password" | "magic-code";
    }
    interface USocialLoginButton {
        /**
          * @default false
         */
        "iconOnly": boolean;
        /**
          * @default "google"
         */
        "provider": SocialLoginProvider;
        /**
          * @default window.location.href
         */
        "redirectUri": string;
        /**
          * @default "light"
         */
        "theme": "light" | "dark";
    }
    interface USpinner {
    }
    interface USubmitButton {
        /**
          * @default ""
         */
        "componentClassName": string;
        /**
          * @default false
         */
        "disabled": boolean;
        "for"?: AuthButtonFor1;
        "text"?: string;
    }
    interface UTicketableList {
        "containerClass"?: string;
        /**
          * @default ""
         */
        "filter": string;
        /**
          * @default 10
         */
        "limit": number;
        /**
          * @default 1
         */
        "page": number;
        /**
          * @default null
         */
        "paginationMeta": PaginationMeta | null;
        /**
          * @default false
         */
        "skeletonAllText"?: boolean;
        "skeletonCount"?: number;
        /**
          * @default null
         */
        "store": PaginationStore | null;
        "target"?: string;
        "ticketableType": "ticket" | "subscription";
    }
}
export interface UConfigCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUConfigElement;
}
export interface ULogoutButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLULogoutButtonElement;
}
export interface USigninRootCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUSigninRootElement;
}
export interface USubmitButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUSubmitButtonElement;
}
declare global {
    interface HTMLNewsletterCheckboxElement extends Components.NewsletterCheckbox, HTMLStencilElement {
    }
    var HTMLNewsletterCheckboxElement: {
        prototype: HTMLNewsletterCheckboxElement;
        new (): HTMLNewsletterCheckboxElement;
    };
    interface HTMLUConditionalRenderElement extends Components.UConditionalRender, HTMLStencilElement {
    }
    var HTMLUConditionalRenderElement: {
        prototype: HTMLUConditionalRenderElement;
        new (): HTMLUConditionalRenderElement;
    };
    interface HTMLUConfigElementEventMap {
        "unidyInitialized": Config;
        "configChange": ConfigChange;
    }
    interface HTMLUConfigElement extends Components.UConfig, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUConfigElementEventMap>(type: K, listener: (this: HTMLUConfigElement, ev: UConfigCustomEvent<HTMLUConfigElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUConfigElementEventMap>(type: K, listener: (this: HTMLUConfigElement, ev: UConfigCustomEvent<HTMLUConfigElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUConfigElement: {
        prototype: HTMLUConfigElement;
        new (): HTMLUConfigElement;
    };
    interface HTMLUEmailFieldElement extends Components.UEmailField, HTMLStencilElement {
    }
    var HTMLUEmailFieldElement: {
        prototype: HTMLUEmailFieldElement;
        new (): HTMLUEmailFieldElement;
    };
    interface HTMLUErrorMessageElement extends Components.UErrorMessage, HTMLStencilElement {
    }
    var HTMLUErrorMessageElement: {
        prototype: HTMLUErrorMessageElement;
        new (): HTMLUErrorMessageElement;
    };
    interface HTMLUFieldElement extends Components.UField, HTMLStencilElement {
    }
    var HTMLUFieldElement: {
        prototype: HTMLUFieldElement;
        new (): HTMLUFieldElement;
    };
    interface HTMLUFlashMessageElement extends Components.UFlashMessage, HTMLStencilElement {
    }
    var HTMLUFlashMessageElement: {
        prototype: HTMLUFlashMessageElement;
        new (): HTMLUFlashMessageElement;
    };
    interface HTMLUFullProfileElement extends Components.UFullProfile, HTMLStencilElement {
    }
    var HTMLUFullProfileElement: {
        prototype: HTMLUFullProfileElement;
        new (): HTMLUFullProfileElement;
    };
    interface HTMLULogoutButtonElementEventMap {
        "logout": void;
    }
    interface HTMLULogoutButtonElement extends Components.ULogoutButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLULogoutButtonElementEventMap>(type: K, listener: (this: HTMLULogoutButtonElement, ev: ULogoutButtonCustomEvent<HTMLULogoutButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLULogoutButtonElementEventMap>(type: K, listener: (this: HTMLULogoutButtonElement, ev: ULogoutButtonCustomEvent<HTMLULogoutButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLULogoutButtonElement: {
        prototype: HTMLULogoutButtonElement;
        new (): HTMLULogoutButtonElement;
    };
    interface HTMLUMagicCodeFieldElement extends Components.UMagicCodeField, HTMLStencilElement {
    }
    var HTMLUMagicCodeFieldElement: {
        prototype: HTMLUMagicCodeFieldElement;
        new (): HTMLUMagicCodeFieldElement;
    };
    interface HTMLUMissingFieldElement extends Components.UMissingField, HTMLStencilElement {
    }
    var HTMLUMissingFieldElement: {
        prototype: HTMLUMissingFieldElement;
        new (): HTMLUMissingFieldElement;
    };
    interface HTMLUMissingFieldsSubmitButtonElement extends Components.UMissingFieldsSubmitButton, HTMLStencilElement {
    }
    var HTMLUMissingFieldsSubmitButtonElement: {
        prototype: HTMLUMissingFieldsSubmitButtonElement;
        new (): HTMLUMissingFieldsSubmitButtonElement;
    };
    interface HTMLUNewsletterRootElement extends Components.UNewsletterRoot, HTMLStencilElement {
    }
    var HTMLUNewsletterRootElement: {
        prototype: HTMLUNewsletterRootElement;
        new (): HTMLUNewsletterRootElement;
    };
    interface HTMLUPaginationButtonElement extends Components.UPaginationButton, HTMLStencilElement {
    }
    var HTMLUPaginationButtonElement: {
        prototype: HTMLUPaginationButtonElement;
        new (): HTMLUPaginationButtonElement;
    };
    interface HTMLUPaginationPageElement extends Components.UPaginationPage, HTMLStencilElement {
    }
    var HTMLUPaginationPageElement: {
        prototype: HTMLUPaginationPageElement;
        new (): HTMLUPaginationPageElement;
    };
    interface HTMLUPasskeyElement extends Components.UPasskey, HTMLStencilElement {
    }
    var HTMLUPasskeyElement: {
        prototype: HTMLUPasskeyElement;
        new (): HTMLUPasskeyElement;
    };
    interface HTMLUPasswordFieldElement extends Components.UPasswordField, HTMLStencilElement {
    }
    var HTMLUPasswordFieldElement: {
        prototype: HTMLUPasswordFieldElement;
        new (): HTMLUPasswordFieldElement;
    };
    interface HTMLUProfileElement extends Components.UProfile, HTMLStencilElement {
    }
    var HTMLUProfileElement: {
        prototype: HTMLUProfileElement;
        new (): HTMLUProfileElement;
    };
    interface HTMLURawFieldElement extends Components.URawField, HTMLStencilElement {
    }
    var HTMLURawFieldElement: {
        prototype: HTMLURawFieldElement;
        new (): HTMLURawFieldElement;
    };
    interface HTMLURegistrationButtonElement extends Components.URegistrationButton, HTMLStencilElement {
    }
    var HTMLURegistrationButtonElement: {
        prototype: HTMLURegistrationButtonElement;
        new (): HTMLURegistrationButtonElement;
    };
    interface HTMLUResetPasswordButtonElement extends Components.UResetPasswordButton, HTMLStencilElement {
    }
    var HTMLUResetPasswordButtonElement: {
        prototype: HTMLUResetPasswordButtonElement;
        new (): HTMLUResetPasswordButtonElement;
    };
    interface HTMLUSendMagicCodeButtonElement extends Components.USendMagicCodeButton, HTMLStencilElement {
    }
    var HTMLUSendMagicCodeButtonElement: {
        prototype: HTMLUSendMagicCodeButtonElement;
        new (): HTMLUSendMagicCodeButtonElement;
    };
    interface HTMLUSignedInElement extends Components.USignedIn, HTMLStencilElement {
    }
    var HTMLUSignedInElement: {
        prototype: HTMLUSignedInElement;
        new (): HTMLUSignedInElement;
    };
    interface HTMLUSigninRootElementEventMap {
        "authEvent": TokenResponse;
        "errorEvent": { error: string };
    }
    interface HTMLUSigninRootElement extends Components.USigninRoot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUSigninRootElementEventMap>(type: K, listener: (this: HTMLUSigninRootElement, ev: USigninRootCustomEvent<HTMLUSigninRootElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUSigninRootElementEventMap>(type: K, listener: (this: HTMLUSigninRootElement, ev: USigninRootCustomEvent<HTMLUSigninRootElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUSigninRootElement: {
        prototype: HTMLUSigninRootElement;
        new (): HTMLUSigninRootElement;
    };
    interface HTMLUSigninStepElement extends Components.USigninStep, HTMLStencilElement {
    }
    var HTMLUSigninStepElement: {
        prototype: HTMLUSigninStepElement;
        new (): HTMLUSigninStepElement;
    };
    interface HTMLUSigninStrategyElement extends Components.USigninStrategy, HTMLStencilElement {
    }
    var HTMLUSigninStrategyElement: {
        prototype: HTMLUSigninStrategyElement;
        new (): HTMLUSigninStrategyElement;
    };
    interface HTMLUSocialLoginButtonElement extends Components.USocialLoginButton, HTMLStencilElement {
    }
    var HTMLUSocialLoginButtonElement: {
        prototype: HTMLUSocialLoginButtonElement;
        new (): HTMLUSocialLoginButtonElement;
    };
    interface HTMLUSpinnerElement extends Components.USpinner, HTMLStencilElement {
    }
    var HTMLUSpinnerElement: {
        prototype: HTMLUSpinnerElement;
        new (): HTMLUSpinnerElement;
    };
    interface HTMLUSubmitButtonElementEventMap {
        "newsletterSuccess": any;
        "newsletterError": any;
    }
    interface HTMLUSubmitButtonElement extends Components.USubmitButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUSubmitButtonElementEventMap>(type: K, listener: (this: HTMLUSubmitButtonElement, ev: USubmitButtonCustomEvent<HTMLUSubmitButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUSubmitButtonElementEventMap>(type: K, listener: (this: HTMLUSubmitButtonElement, ev: USubmitButtonCustomEvent<HTMLUSubmitButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUSubmitButtonElement: {
        prototype: HTMLUSubmitButtonElement;
        new (): HTMLUSubmitButtonElement;
    };
    interface HTMLUTicketableListElement extends Components.UTicketableList, HTMLStencilElement {
    }
    var HTMLUTicketableListElement: {
        prototype: HTMLUTicketableListElement;
        new (): HTMLUTicketableListElement;
    };
    interface HTMLElementTagNameMap {
        "newsletter-checkbox": HTMLNewsletterCheckboxElement;
        "u-conditional-render": HTMLUConditionalRenderElement;
        "u-config": HTMLUConfigElement;
        "u-email-field": HTMLUEmailFieldElement;
        "u-error-message": HTMLUErrorMessageElement;
        "u-field": HTMLUFieldElement;
        "u-flash-message": HTMLUFlashMessageElement;
        "u-full-profile": HTMLUFullProfileElement;
        "u-logout-button": HTMLULogoutButtonElement;
        "u-magic-code-field": HTMLUMagicCodeFieldElement;
        "u-missing-field": HTMLUMissingFieldElement;
        "u-missing-fields-submit-button": HTMLUMissingFieldsSubmitButtonElement;
        "u-newsletter-root": HTMLUNewsletterRootElement;
        "u-pagination-button": HTMLUPaginationButtonElement;
        "u-pagination-page": HTMLUPaginationPageElement;
        "u-passkey": HTMLUPasskeyElement;
        "u-password-field": HTMLUPasswordFieldElement;
        "u-profile": HTMLUProfileElement;
        "u-raw-field": HTMLURawFieldElement;
        "u-registration-button": HTMLURegistrationButtonElement;
        "u-reset-password-button": HTMLUResetPasswordButtonElement;
        "u-send-magic-code-button": HTMLUSendMagicCodeButtonElement;
        "u-signed-in": HTMLUSignedInElement;
        "u-signin-root": HTMLUSigninRootElement;
        "u-signin-step": HTMLUSigninStepElement;
        "u-signin-strategy": HTMLUSigninStrategyElement;
        "u-social-login-button": HTMLUSocialLoginButtonElement;
        "u-spinner": HTMLUSpinnerElement;
        "u-submit-button": HTMLUSubmitButtonElement;
        "u-ticketable-list": HTMLUTicketableListElement;
    }
}
declare namespace LocalJSX {
    interface NewsletterCheckbox {
        "checked"?: boolean;
        "componentClassName"?: string;
        "internalName"?: string;
        "label"?: string;
    }
    interface UConditionalRender {
        "conditionFunction"?: (state: AuthState) => boolean;
        "is"?: string;
        /**
          * @default false
         */
        "not"?: boolean;
        "when"?: string;
    }
    interface UConfig {
        /**
          * @default ""
         */
        "apiKey"?: string;
        /**
          * @default ""
         */
        "baseUrl"?: string;
        /**
          * @default ""
         */
        "customTranslations"?: string | Record<string, TranslationTree>;
        /**
          * @default "en"
         */
        "fallbackLocale"?: string;
        /**
          * @default "en"
         */
        "locale"?: string;
        /**
          * @default "production"
         */
        "mode"?: "production" | "development";
        "onConfigChange"?: (event: UConfigCustomEvent<ConfigChange>) => void;
        "onUnidyInitialized"?: (event: UConfigCustomEvent<Config>) => void;
    }
    interface UEmailField {
        /**
          * @default "Email"
         */
        "ariaLabel"?: string;
        /**
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "placeholder"?: string;
    }
    interface UErrorMessage {
        /**
          * @default ""
         */
        "componentClassName"?: string;
        "errorMessages"?: Record<string, string>;
        "for": "email" | "password" | "magicCode" | "resetPassword" | "general" | "connection";
    }
    interface UField {
        "componentClassName"?: string;
        /**
          * @default "label"
         */
        "countryCodeDisplayOption"?: "icon" | "label";
        /**
          * @default true
         */
        "emptyOption"?: boolean;
        "field": string;
        /**
          * @default "Please enter a valid phone number."
         */
        "invalidPhoneMessage"?: string;
        "pattern"?: string;
        "patternErrorMessage"?: string;
        "placeholder"?: string;
        /**
          * @default "No information"
         */
        "readonlyPlaceholder"?: string;
        /**
          * @default true
         */
        "renderDefaultLabel"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        "validationFunc"?: (value: string | string[]) => { valid: boolean; message?: string };
    }
    interface UFlashMessage {
        /**
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * @default null
         */
        "removeAfterSeconds"?: number | null;
    }
    interface UFullProfile {
        /**
          * @default "label"
         */
        "countryCodeDisplayOption"?: "icon" | "label";
        "fields"?: string;
        /**
          * @default ""
         */
        "submitButtonText"?: string;
    }
    interface ULogoutButton {
        /**
          * @default ""
         */
        "componentClassName"?: string;
        "onLogout"?: (event: ULogoutButtonCustomEvent<void>) => void;
        /**
          * @default true
         */
        "reloadOnSuccess"?: boolean;
    }
    interface UMagicCodeField {
        /**
          * @default ""
         */
        "componentClassName"?: string;
    }
    interface UMissingField {
    }
    interface UMissingFieldsSubmitButton {
    }
    interface UNewsletterRoot {
        /**
          * @default ""
         */
        "componentClassName"?: string;
    }
    interface UPaginationButton {
        "customClass"?: string;
        /**
          * @default "next"
         */
        "direction"?: "prev" | "next";
    }
    interface UPaginationPage {
        "customClass"?: string;
    }
    interface UPasskey {
        /**
          * @default ""
         */
        "ariaDescribedBy"?: string;
        /**
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
    }
    interface UPasswordField {
        /**
          * @default ""
         */
        "ariaLabel"?: string;
        /**
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * @default "login"
         */
        "for"?: PasswordFieldFor;
        /**
          * @default null
         */
        "placeholder"?: any;
    }
    interface UProfile {
        /**
          * @default ""
         */
        "initialData"?: string | Record<string, string>;
        "profileId"?: string;
    }
    interface URawField {
        /**
          * @default ""
         */
        "ariaDescribedBy"?: string;
        "attrName"?: string;
        "checked"?: boolean;
        "componentClassName"?: string;
        /**
          * @default "label"
         */
        "countryCodeDisplayOption"?: "icon" | "label";
        "disabled"?: boolean;
        /**
          * @default false
         */
        "emptyOption"?: boolean;
        "field": string;
        /**
          * @default "Please enter a valid phone number."
         */
        "invalidPhoneMessage"?: string;
        "multiSelectOptions"?: MultiSelectOption[];
        "options"?: string | Option[];
        "pattern"?: string;
        "patternErrorMessage"?: string;
        "placeholder"?: string;
        "radioOptions"?: RadioOption[];
        /**
          * @default ""
         */
        "readonlyPlaceholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        "specificPartKey"?: string;
        "tooltip"?: string;
        "type": string;
        "validationFunc"?: (value: string | string[]) => { valid: boolean; message?: string };
        "value"?: string | string[];
    }
    interface URegistrationButton {
        /**
          * @default ""
         */
        "componentClassName"?: string;
        "for": "email";
        /**
          * @default window.location.href
         */
        "redirectUri"?: string;
    }
    interface UResetPasswordButton {
        /**
          * @default ""
         */
        "componentClassName"?: string;
    }
    interface USendMagicCodeButton {
        /**
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
    }
    interface USignedIn {
        /**
          * @default ""
         */
        "componentClassName"?: string;
    }
    interface USigninRoot {
        /**
          * @default ""
         */
        "componentClassName"?: string;
        "onAuthEvent"?: (event: USigninRootCustomEvent<TokenResponse>) => void;
        "onErrorEvent"?: (event: USigninRootCustomEvent<{ error: string }>) => void;
    }
    interface USigninStep {
        /**
          * @default false
         */
        "alwaysRender"?: boolean;
        "name": "email" | "verification" | "reset-password" | "registration";
    }
    interface USigninStrategy {
        /**
          * @default ""
         */
        "componentClassName"?: string;
        "type": "password" | "magic-code";
    }
    interface USocialLoginButton {
        /**
          * @default false
         */
        "iconOnly"?: boolean;
        /**
          * @default "google"
         */
        "provider"?: SocialLoginProvider;
        /**
          * @default window.location.href
         */
        "redirectUri"?: string;
        /**
          * @default "light"
         */
        "theme"?: "light" | "dark";
    }
    interface USpinner {
    }
    interface USubmitButton {
        /**
          * @default ""
         */
        "componentClassName"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "for"?: AuthButtonFor1;
        "onNewsletterError"?: (event: USubmitButtonCustomEvent<any>) => void;
        "onNewsletterSuccess"?: (event: USubmitButtonCustomEvent<any>) => void;
        "text"?: string;
    }
    interface UTicketableList {
        "containerClass"?: string;
        /**
          * @default ""
         */
        "filter"?: string;
        /**
          * @default 10
         */
        "limit"?: number;
        /**
          * @default 1
         */
        "page"?: number;
        /**
          * @default null
         */
        "paginationMeta"?: PaginationMeta | null;
        /**
          * @default false
         */
        "skeletonAllText"?: boolean;
        "skeletonCount"?: number;
        /**
          * @default null
         */
        "store"?: PaginationStore | null;
        "target"?: string;
        "ticketableType": "ticket" | "subscription";
    }
    interface IntrinsicElements {
        "newsletter-checkbox": NewsletterCheckbox;
        "u-conditional-render": UConditionalRender;
        "u-config": UConfig;
        "u-email-field": UEmailField;
        "u-error-message": UErrorMessage;
        "u-field": UField;
        "u-flash-message": UFlashMessage;
        "u-full-profile": UFullProfile;
        "u-logout-button": ULogoutButton;
        "u-magic-code-field": UMagicCodeField;
        "u-missing-field": UMissingField;
        "u-missing-fields-submit-button": UMissingFieldsSubmitButton;
        "u-newsletter-root": UNewsletterRoot;
        "u-pagination-button": UPaginationButton;
        "u-pagination-page": UPaginationPage;
        "u-passkey": UPasskey;
        "u-password-field": UPasswordField;
        "u-profile": UProfile;
        "u-raw-field": URawField;
        "u-registration-button": URegistrationButton;
        "u-reset-password-button": UResetPasswordButton;
        "u-send-magic-code-button": USendMagicCodeButton;
        "u-signed-in": USignedIn;
        "u-signin-root": USigninRoot;
        "u-signin-step": USigninStep;
        "u-signin-strategy": USigninStrategy;
        "u-social-login-button": USocialLoginButton;
        "u-spinner": USpinner;
        "u-submit-button": USubmitButton;
        "u-ticketable-list": UTicketableList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "newsletter-checkbox": LocalJSX.NewsletterCheckbox & JSXBase.HTMLAttributes<HTMLNewsletterCheckboxElement>;
            "u-conditional-render": LocalJSX.UConditionalRender & JSXBase.HTMLAttributes<HTMLUConditionalRenderElement>;
            "u-config": LocalJSX.UConfig & JSXBase.HTMLAttributes<HTMLUConfigElement>;
            "u-email-field": LocalJSX.UEmailField & JSXBase.HTMLAttributes<HTMLUEmailFieldElement>;
            "u-error-message": LocalJSX.UErrorMessage & JSXBase.HTMLAttributes<HTMLUErrorMessageElement>;
            "u-field": LocalJSX.UField & JSXBase.HTMLAttributes<HTMLUFieldElement>;
            "u-flash-message": LocalJSX.UFlashMessage & JSXBase.HTMLAttributes<HTMLUFlashMessageElement>;
            "u-full-profile": LocalJSX.UFullProfile & JSXBase.HTMLAttributes<HTMLUFullProfileElement>;
            "u-logout-button": LocalJSX.ULogoutButton & JSXBase.HTMLAttributes<HTMLULogoutButtonElement>;
            "u-magic-code-field": LocalJSX.UMagicCodeField & JSXBase.HTMLAttributes<HTMLUMagicCodeFieldElement>;
            "u-missing-field": LocalJSX.UMissingField & JSXBase.HTMLAttributes<HTMLUMissingFieldElement>;
            "u-missing-fields-submit-button": LocalJSX.UMissingFieldsSubmitButton & JSXBase.HTMLAttributes<HTMLUMissingFieldsSubmitButtonElement>;
            "u-newsletter-root": LocalJSX.UNewsletterRoot & JSXBase.HTMLAttributes<HTMLUNewsletterRootElement>;
            "u-pagination-button": LocalJSX.UPaginationButton & JSXBase.HTMLAttributes<HTMLUPaginationButtonElement>;
            "u-pagination-page": LocalJSX.UPaginationPage & JSXBase.HTMLAttributes<HTMLUPaginationPageElement>;
            "u-passkey": LocalJSX.UPasskey & JSXBase.HTMLAttributes<HTMLUPasskeyElement>;
            "u-password-field": LocalJSX.UPasswordField & JSXBase.HTMLAttributes<HTMLUPasswordFieldElement>;
            "u-profile": LocalJSX.UProfile & JSXBase.HTMLAttributes<HTMLUProfileElement>;
            "u-raw-field": LocalJSX.URawField & JSXBase.HTMLAttributes<HTMLURawFieldElement>;
            "u-registration-button": LocalJSX.URegistrationButton & JSXBase.HTMLAttributes<HTMLURegistrationButtonElement>;
            "u-reset-password-button": LocalJSX.UResetPasswordButton & JSXBase.HTMLAttributes<HTMLUResetPasswordButtonElement>;
            "u-send-magic-code-button": LocalJSX.USendMagicCodeButton & JSXBase.HTMLAttributes<HTMLUSendMagicCodeButtonElement>;
            "u-signed-in": LocalJSX.USignedIn & JSXBase.HTMLAttributes<HTMLUSignedInElement>;
            "u-signin-root": LocalJSX.USigninRoot & JSXBase.HTMLAttributes<HTMLUSigninRootElement>;
            "u-signin-step": LocalJSX.USigninStep & JSXBase.HTMLAttributes<HTMLUSigninStepElement>;
            "u-signin-strategy": LocalJSX.USigninStrategy & JSXBase.HTMLAttributes<HTMLUSigninStrategyElement>;
            "u-social-login-button": LocalJSX.USocialLoginButton & JSXBase.HTMLAttributes<HTMLUSocialLoginButtonElement>;
            "u-spinner": LocalJSX.USpinner & JSXBase.HTMLAttributes<HTMLUSpinnerElement>;
            "u-submit-button": LocalJSX.USubmitButton & JSXBase.HTMLAttributes<HTMLUSubmitButtonElement>;
            "u-ticketable-list": LocalJSX.UTicketableList & JSXBase.HTMLAttributes<HTMLUTicketableListElement>;
        }
    }
}
