/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from '../newsletter-react/lib/index';

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type ReactWebComponent, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';
import type { NewsletterSubscription, NewsletterSubscriptionError, UnidyNewsletterCustomEvent } from "@unidy.io/newsletter";
import type { UnidyNewsletter as UnidyNewsletterElement } from "@unidy.io/newsletter/dist/per-component/unidy-newsletter.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type UnidyNewsletterEvents = {
    onSuccess: EventName<UnidyNewsletterCustomEvent<NewsletterSubscription[]>>,
    onError: EventName<UnidyNewsletterCustomEvent<NewsletterSubscriptionError[]>>,
    onResetStatus: EventName<CustomEvent<void>>
};

export const UnidyNewsletter: StencilReactComponent<UnidyNewsletterElement, UnidyNewsletterEvents> = /*@__PURE__*/ createComponent<UnidyNewsletterElement, UnidyNewsletterEvents>({
    tagName: 'unidy-newsletter',
    properties: {
        header: 'header',
        newslettersConfig: 'newsletters-config',
        newslettersConfigJson: 'newsletters-config-json',
        additionalFields: 'additional-fields',
        additionalFieldsConfigJson: 'additional-fields-config-json',
        submitButtonText: 'submit-button-text',
        emailLabel: 'email-label',
        emailPlaceholder: 'email-placeholder',
        apiUrl: 'api-url',
        apiKey: 'api-key',
        returnToAfterConfirmation: 'return-to-after-confirmation',
        renderErrorMessages: 'render-error-messages',
        errorUnconfirmedText: 'error-unconfirmed-text',
        errorAlreadySubscribedText: 'error-already-subscribed-text',
        errorInvalidEmailText: 'error-invalid-email-text',
        errorNewsletterNotFoundText: 'error-newsletter-not-found-text',
        errorPreferenceNotFoundText: 'error-preference-not-found-text',
        errorUnknownText: 'error-unknown-text',
        errorResendConfirmationActionText: 'error-resend-confirmation-action-text',
        errorResendConfirmationSuccessText: 'error-resend-confirmation-success-text',
        successConfirmationText: 'success-confirmation-text',
        confirmationErrorText: 'confirmation-error-text'
    },
    hydrateModule: import('../../../../newsletter/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.UnidyNewsletter as ReactWebComponent<UnidyNewsletterElement, UnidyNewsletterEvents>,
    serializeShadowRoot,
});
