'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import type { NewsletterSubscription, NewsletterSubscriptionError, UnidyNewsletterCustomEvent } from "@unidy.io/newsletter";
import { UnidyNewsletter as UnidyNewsletterElement, defineCustomElement as defineUnidyNewsletter } from "@unidy.io/newsletter/dist/per-component/unidy-newsletter.js";
import React from 'react';

export type UnidyNewsletterEvents = {
    onSuccess: EventName<UnidyNewsletterCustomEvent<NewsletterSubscription[]>>,
    onError: EventName<UnidyNewsletterCustomEvent<NewsletterSubscriptionError[]>>,
    onResetStatus: EventName<CustomEvent<void>>
};

export const UnidyNewsletter: StencilReactComponent<UnidyNewsletterElement, UnidyNewsletterEvents> = /*@__PURE__*/ createComponent<UnidyNewsletterElement, UnidyNewsletterEvents>({
    tagName: 'unidy-newsletter',
    elementClass: UnidyNewsletterElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onSuccess: 'success',
        onError: 'error',
        onResetStatus: 'resetStatus'
    } as UnidyNewsletterEvents,
    defineCustomElement: defineUnidyNewsletter
});
