/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UnidyLogin {
        "auth": ({ trySilentAuth }?: { trySilentAuth?: boolean; }) => Promise<AuthResult>;
        /**
          * The base URL of the Unidy authentication server, example: https://your-domain.unidy.de
         */
        "baseUrl": string;
        /**
          * The client ID for the application
         */
        "clientId": string;
        "hide": () => Promise<void>;
        "logout": () => Promise<LogoutResult>;
        /**
          * The prompt option for authentication, can be "none", "login", "consent", "select_account" or null
         */
        "prompt": PromptOption;
        /**
          * The URL to redirect to after authentication, defaults to current origin
         */
        "redirectUrl": string;
        /**
          * The OAuth response type, defaults to "id_token"
         */
        "responseType": string;
        /**
          * The OAuth scopes to request, defaults to "openid email"
         */
        "scope": string;
        "show": () => Promise<void>;
    }
}
export interface UnidyLoginCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUnidyLoginElement;
}
declare global {
    interface HTMLUnidyLoginElementEventMap {
        "Auth": { token: string };
    }
    interface HTMLUnidyLoginElement extends Components.UnidyLogin, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUnidyLoginElementEventMap>(type: K, listener: (this: HTMLUnidyLoginElement, ev: UnidyLoginCustomEvent<HTMLUnidyLoginElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUnidyLoginElementEventMap>(type: K, listener: (this: HTMLUnidyLoginElement, ev: UnidyLoginCustomEvent<HTMLUnidyLoginElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUnidyLoginElement: {
        prototype: HTMLUnidyLoginElement;
        new (): HTMLUnidyLoginElement;
    };
    interface HTMLElementTagNameMap {
        "unidy-login": HTMLUnidyLoginElement;
    }
}
declare namespace LocalJSX {
    interface UnidyLogin {
        /**
          * The base URL of the Unidy authentication server, example: https://your-domain.unidy.de
         */
        "baseUrl": string;
        /**
          * The client ID for the application
         */
        "clientId": string;
        "onAuth"?: (event: UnidyLoginCustomEvent<{ token: string }>) => void;
        /**
          * The prompt option for authentication, can be "none", "login", "consent", "select_account" or null
         */
        "prompt"?: PromptOption;
        /**
          * The URL to redirect to after authentication, defaults to current origin
         */
        "redirectUrl"?: string;
        /**
          * The OAuth response type, defaults to "id_token"
         */
        "responseType"?: string;
        /**
          * The OAuth scopes to request, defaults to "openid email"
         */
        "scope"?: string;
    }
    interface IntrinsicElements {
        "unidy-login": UnidyLogin;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "unidy-login": LocalJSX.UnidyLogin & JSXBase.HTMLAttributes<HTMLUnidyLoginElement>;
        }
    }
}
