/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UnidyLogin {
        "auth": (trySilentAuth?: boolean) => Promise<AuthResult>;
        "baseUrl": string;
        "clientId": string;
        "hide": () => Promise<void>;
        "logout": () => Promise<void>;
        "prompt": PromptOption;
        "redirectUrl": string;
        "responseType": string;
        "scope": string;
        "show": () => Promise<void>;
    }
}
export interface UnidyLoginCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUnidyLoginElement;
}
declare global {
    interface HTMLUnidyLoginElementEventMap {
        "onAuth": { token: string };
    }
    interface HTMLUnidyLoginElement extends Components.UnidyLogin, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUnidyLoginElementEventMap>(type: K, listener: (this: HTMLUnidyLoginElement, ev: UnidyLoginCustomEvent<HTMLUnidyLoginElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUnidyLoginElementEventMap>(type: K, listener: (this: HTMLUnidyLoginElement, ev: UnidyLoginCustomEvent<HTMLUnidyLoginElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUnidyLoginElement: {
        prototype: HTMLUnidyLoginElement;
        new (): HTMLUnidyLoginElement;
    };
    interface HTMLElementTagNameMap {
        "unidy-login": HTMLUnidyLoginElement;
    }
}
declare namespace LocalJSX {
    interface UnidyLogin {
        "baseUrl": string;
        "clientId": string;
        "onOnAuth"?: (event: UnidyLoginCustomEvent<{ token: string }>) => void;
        "prompt"?: PromptOption;
        "redirectUrl"?: string;
        "responseType"?: string;
        "scope"?: string;
    }
    interface IntrinsicElements {
        "unidy-login": UnidyLogin;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "unidy-login": LocalJSX.UnidyLogin & JSXBase.HTMLAttributes<HTMLUnidyLoginElement>;
        }
    }
}
