/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { NewsletterConfig } from "./components/newsletter/newsletter";
import { NewsletterSubscription, NewsletterSubscriptionError } from "@unidy.io/sdk-api-client";
export { NewsletterConfig } from "./components/newsletter/newsletter";
export { NewsletterSubscription, NewsletterSubscriptionError } from "@unidy.io/sdk-api-client";
export namespace Components {
    interface UnidyNewsletter {
        /**
          * @default []
         */
        "additionalFields": { name: string; label: string; type: string; required?: boolean }[];
        "additionalFieldsConfigJson": string;
        "apiKey": string;
        "apiUrl": string;
        /**
          * @default "Your preference token could not be assigned. Enter your e-mail address to receive a new link."
         */
        "confirmationErrorText": string;
        /**
          * @default "Email"
         */
        "emailLabel": string;
        /**
          * @default "Email"
         */
        "emailPlaceholder": string;
        /**
          * @default "Already subscribed"
         */
        "errorAlreadySubscribedText": string;
        /**
          * @default "Invalid email address"
         */
        "errorInvalidEmailText": string;
        /**
          * @default "Newsletter not found"
         */
        "errorNewsletterNotFoundText": string;
        /**
          * @default "Preference not found"
         */
        "errorPreferenceNotFoundText": string;
        /**
          * @default "Email not confirmed"
         */
        "errorUnconfirmedText": string;
        /**
          * @default "Unknown error occured"
         */
        "errorUnknownText": string;
        "header": string;
        /**
          * @default []
         */
        "newslettersConfig": NewsletterConfig[];
        "newslettersConfigJson": string;
        /**
          * @default false
         */
        "renderErrorMessages": boolean;
        "returnToAfterConfirmation"?: string;
        /**
          * @default "Subscribe"
         */
        "submitButtonText": string;
        /**
          * @default "You have successfully confirmed your newsletter subscription."
         */
        "successConfirmationText": string;
    }
}
export interface UnidyNewsletterCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUnidyNewsletterElement;
}
declare global {
    interface HTMLUnidyNewsletterElementEventMap {
        "on:success": NewsletterSubscription[];
        "on:error": NewsletterSubscriptionError[];
        "resetStatus": void;
    }
    interface HTMLUnidyNewsletterElement extends Components.UnidyNewsletter, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUnidyNewsletterElementEventMap>(type: K, listener: (this: HTMLUnidyNewsletterElement, ev: UnidyNewsletterCustomEvent<HTMLUnidyNewsletterElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUnidyNewsletterElementEventMap>(type: K, listener: (this: HTMLUnidyNewsletterElement, ev: UnidyNewsletterCustomEvent<HTMLUnidyNewsletterElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUnidyNewsletterElement: {
        prototype: HTMLUnidyNewsletterElement;
        new (): HTMLUnidyNewsletterElement;
    };
    interface HTMLElementTagNameMap {
        "unidy-newsletter": HTMLUnidyNewsletterElement;
    }
}
declare namespace LocalJSX {
    interface UnidyNewsletter {
        /**
          * @default []
         */
        "additionalFields"?: { name: string; label: string; type: string; required?: boolean }[];
        "additionalFieldsConfigJson"?: string;
        "apiKey"?: string;
        "apiUrl"?: string;
        /**
          * @default "Your preference token could not be assigned. Enter your e-mail address to receive a new link."
         */
        "confirmationErrorText"?: string;
        /**
          * @default "Email"
         */
        "emailLabel"?: string;
        /**
          * @default "Email"
         */
        "emailPlaceholder"?: string;
        /**
          * @default "Already subscribed"
         */
        "errorAlreadySubscribedText"?: string;
        /**
          * @default "Invalid email address"
         */
        "errorInvalidEmailText"?: string;
        /**
          * @default "Newsletter not found"
         */
        "errorNewsletterNotFoundText"?: string;
        /**
          * @default "Preference not found"
         */
        "errorPreferenceNotFoundText"?: string;
        /**
          * @default "Email not confirmed"
         */
        "errorUnconfirmedText"?: string;
        /**
          * @default "Unknown error occured"
         */
        "errorUnknownText"?: string;
        "header"?: string;
        /**
          * @default []
         */
        "newslettersConfig"?: NewsletterConfig[];
        "newslettersConfigJson"?: string;
        "onOn:error"?: (event: UnidyNewsletterCustomEvent<NewsletterSubscriptionError[]>) => void;
        "onOn:success"?: (event: UnidyNewsletterCustomEvent<NewsletterSubscription[]>) => void;
        "onResetStatus"?: (event: UnidyNewsletterCustomEvent<void>) => void;
        /**
          * @default false
         */
        "renderErrorMessages"?: boolean;
        "returnToAfterConfirmation"?: string;
        /**
          * @default "Subscribe"
         */
        "submitButtonText"?: string;
        /**
          * @default "You have successfully confirmed your newsletter subscription."
         */
        "successConfirmationText"?: string;
    }
    interface IntrinsicElements {
        "unidy-newsletter": UnidyNewsletter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "unidy-newsletter": LocalJSX.UnidyNewsletter & JSXBase.HTMLAttributes<HTMLUnidyNewsletterElement>;
        }
    }
}
