/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { NewsletterSubscription, NewsletterSubscriptionError } from "@unidy.io/sdk-api-client";
export { NewsletterSubscription, NewsletterSubscriptionError } from "@unidy.io/sdk-api-client";
export namespace Components {
    interface UnidyNewsletter {
        "apiKey": string;
        "apiUrl": string;
        "defaultNewsletterInternalName": string;
        "emailLabel": string;
        "emailPlaceholder": string;
        "errorAlreadySubscribedText": string;
        "errorInvalidEmailText": string;
        "errorUnconfirmedText": string;
        "errorUnknownText": string;
        "header": string;
        "newslettersConfig": { internal_name: string; label: string; checked?: boolean }[];
        "redirect_to"?: string;
        "renderErrorMessages": boolean;
        "status"?: string;
        "submitButtonText": string;
    }
}
export interface UnidyNewsletterCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUnidyNewsletterElement;
}
declare global {
    interface HTMLUnidyNewsletterElementEventMap {
        "on:success": NewsletterSubscription[];
        "on:error": NewsletterSubscriptionError[];
    }
    interface HTMLUnidyNewsletterElement extends Components.UnidyNewsletter, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUnidyNewsletterElementEventMap>(type: K, listener: (this: HTMLUnidyNewsletterElement, ev: UnidyNewsletterCustomEvent<HTMLUnidyNewsletterElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUnidyNewsletterElementEventMap>(type: K, listener: (this: HTMLUnidyNewsletterElement, ev: UnidyNewsletterCustomEvent<HTMLUnidyNewsletterElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUnidyNewsletterElement: {
        prototype: HTMLUnidyNewsletterElement;
        new (): HTMLUnidyNewsletterElement;
    };
    interface HTMLElementTagNameMap {
        "unidy-newsletter": HTMLUnidyNewsletterElement;
    }
}
declare namespace LocalJSX {
    interface UnidyNewsletter {
        "apiKey"?: string;
        "apiUrl"?: string;
        "defaultNewsletterInternalName"?: string;
        "emailLabel"?: string;
        "emailPlaceholder"?: string;
        "errorAlreadySubscribedText"?: string;
        "errorInvalidEmailText"?: string;
        "errorUnconfirmedText"?: string;
        "errorUnknownText"?: string;
        "header"?: string;
        "newslettersConfig"?: { internal_name: string; label: string; checked?: boolean }[];
        "onOn:error"?: (event: UnidyNewsletterCustomEvent<NewsletterSubscriptionError[]>) => void;
        "onOn:success"?: (event: UnidyNewsletterCustomEvent<NewsletterSubscription[]>) => void;
        "redirect_to"?: string;
        "renderErrorMessages"?: boolean;
        "status"?: string;
        "submitButtonText"?: string;
    }
    interface IntrinsicElements {
        "unidy-newsletter": UnidyNewsletter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "unidy-newsletter": LocalJSX.UnidyNewsletter & JSXBase.HTMLAttributes<HTMLUnidyNewsletterElement>;
        }
    }
}
