/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { PaginationStore } from "../store/pagination-store";
export { PaginationStore } from "../store/pagination-store";
export namespace Components {
    interface UPaginationButton {
        "customClass"?: string;
        /**
          * @default 'next'
         */
        "direction": 'prev' | 'next';
    }
    interface UPaginationPage {
        "customClass"?: string;
    }
    interface UTicketableList {
        /**
          * @default 'public-newsletter-api-key'
         */
        "apiKey"?: string;
        /**
          * @default 'http://localhost:3000'
         */
        "baseUrl"?: string;
        "containerClass"?: string;
        /**
          * @default ''
         */
        "filter": string;
        /**
          * @default 10
         */
        "limit": number;
        /**
          * @default 'en-US'
         */
        "locale"?: string;
        /**
          * @default 1
         */
        "page": number;
        /**
          * @default null
         */
        "paginationMeta": PaginationMeta | null;
        /**
          * @default false
         */
        "skeletonAllText"?: boolean;
        "skeletonCount"?: number;
        /**
          * @default null
         */
        "store": PaginationStore | null;
        "target"?: string;
        "ticketableType": 'ticket' | 'subscription';
    }
}
declare global {
    interface HTMLUPaginationButtonElement extends Components.UPaginationButton, HTMLStencilElement {
    }
    var HTMLUPaginationButtonElement: {
        prototype: HTMLUPaginationButtonElement;
        new (): HTMLUPaginationButtonElement;
    };
    interface HTMLUPaginationPageElement extends Components.UPaginationPage, HTMLStencilElement {
    }
    var HTMLUPaginationPageElement: {
        prototype: HTMLUPaginationPageElement;
        new (): HTMLUPaginationPageElement;
    };
    interface HTMLUTicketableListElement extends Components.UTicketableList, HTMLStencilElement {
    }
    var HTMLUTicketableListElement: {
        prototype: HTMLUTicketableListElement;
        new (): HTMLUTicketableListElement;
    };
    interface HTMLElementTagNameMap {
        "u-pagination-button": HTMLUPaginationButtonElement;
        "u-pagination-page": HTMLUPaginationPageElement;
        "u-ticketable-list": HTMLUTicketableListElement;
    }
}
declare namespace LocalJSX {
    interface UPaginationButton {
        "customClass"?: string;
        /**
          * @default 'next'
         */
        "direction"?: 'prev' | 'next';
    }
    interface UPaginationPage {
        "customClass"?: string;
    }
    interface UTicketableList {
        /**
          * @default 'public-newsletter-api-key'
         */
        "apiKey"?: string;
        /**
          * @default 'http://localhost:3000'
         */
        "baseUrl"?: string;
        "containerClass"?: string;
        /**
          * @default ''
         */
        "filter"?: string;
        /**
          * @default 10
         */
        "limit"?: number;
        /**
          * @default 'en-US'
         */
        "locale"?: string;
        /**
          * @default 1
         */
        "page"?: number;
        /**
          * @default null
         */
        "paginationMeta"?: PaginationMeta | null;
        /**
          * @default false
         */
        "skeletonAllText"?: boolean;
        "skeletonCount"?: number;
        /**
          * @default null
         */
        "store"?: PaginationStore | null;
        "target"?: string;
        "ticketableType": 'ticket' | 'subscription';
    }
    interface IntrinsicElements {
        "u-pagination-button": UPaginationButton;
        "u-pagination-page": UPaginationPage;
        "u-ticketable-list": UTicketableList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "u-pagination-button": LocalJSX.UPaginationButton & JSXBase.HTMLAttributes<HTMLUPaginationButtonElement>;
            "u-pagination-page": LocalJSX.UPaginationPage & JSXBase.HTMLAttributes<HTMLUPaginationPageElement>;
            "u-ticketable-list": LocalJSX.UTicketableList & JSXBase.HTMLAttributes<HTMLUTicketableListElement>;
        }
    }
}
