/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TicketableList {
        "containerClass"?: string;
        "filter"?: string;
    }
}
declare global {
    interface HTMLTicketableListElement extends Components.TicketableList, HTMLStencilElement {
    }
    var HTMLTicketableListElement: {
        prototype: HTMLTicketableListElement;
        new (): HTMLTicketableListElement;
    };
    interface HTMLElementTagNameMap {
        "ticketable-list": HTMLTicketableListElement;
    }
}
declare namespace LocalJSX {
    interface TicketableList {
        "containerClass"?: string;
        "filter"?: string;
    }
    interface IntrinsicElements {
        "ticketable-list": TicketableList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ticketable-list": LocalJSX.TicketableList & JSXBase.HTMLAttributes<HTMLTicketableListElement>;
        }
    }
}
