/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ObservableMap } from "@stencil/store";
import { ProfileStore } from "./components/unidy-profile/unidy-profile";
export { ObservableMap } from "@stencil/store";
export { ProfileStore } from "./components/unidy-profile/unidy-profile";
export namespace Components {
    interface SubmitButton {
    }
    interface UnidyField {
        "field": string;
    }
    interface UnidyProfile {
        "id": string;
        "initialData": string | Record<string, string>;
        "store": ObservableMap<ProfileStore>;
    }
}
declare global {
    interface HTMLSubmitButtonElement extends Components.SubmitButton, HTMLStencilElement {
    }
    var HTMLSubmitButtonElement: {
        prototype: HTMLSubmitButtonElement;
        new (): HTMLSubmitButtonElement;
    };
    interface HTMLUnidyFieldElement extends Components.UnidyField, HTMLStencilElement {
    }
    var HTMLUnidyFieldElement: {
        prototype: HTMLUnidyFieldElement;
        new (): HTMLUnidyFieldElement;
    };
    interface HTMLUnidyProfileElement extends Components.UnidyProfile, HTMLStencilElement {
    }
    var HTMLUnidyProfileElement: {
        prototype: HTMLUnidyProfileElement;
        new (): HTMLUnidyProfileElement;
    };
    interface HTMLElementTagNameMap {
        "submit-button": HTMLSubmitButtonElement;
        "unidy-field": HTMLUnidyFieldElement;
        "unidy-profile": HTMLUnidyProfileElement;
    }
}
declare namespace LocalJSX {
    interface SubmitButton {
    }
    interface UnidyField {
        "field"?: string;
    }
    interface UnidyProfile {
        "id"?: string;
        "initialData"?: string | Record<string, string>;
        "store"?: ObservableMap<ProfileStore>;
    }
    interface IntrinsicElements {
        "submit-button": SubmitButton;
        "unidy-field": UnidyField;
        "unidy-profile": UnidyProfile;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "submit-button": LocalJSX.SubmitButton & JSXBase.HTMLAttributes<HTMLSubmitButtonElement>;
            "unidy-field": LocalJSX.UnidyField & JSXBase.HTMLAttributes<HTMLUnidyFieldElement>;
            "unidy-profile": LocalJSX.UnidyProfile & JSXBase.HTMLAttributes<HTMLUnidyProfileElement>;
        }
    }
}
