/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ObservableMap } from "@stencil/store";
import { ProfileStore } from "./components/unidy-profile/unidy-profile";
export { ObservableMap } from "@stencil/store";
export { ProfileStore } from "./components/unidy-profile/unidy-profile";
export namespace Components {
    interface FlashMessage {
        /**
          * @default ""
         */
        "message": string;
        /**
          * @default "info"
         */
        "variant": "error" | "success" | "info";
    }
    interface SubmitButton {
    }
    interface UnidyField {
        "field": string;
        /**
          * @default false
         */
        "required": boolean;
    }
    interface UnidyProfile {
        "apiKey"?: string;
        "apiUrl"?: string;
        /**
          * @default ""
         */
        "initialData": string | Record<string, string>;
        "profileId"?: string;
        /**
          * @default createStore<ProfileStore>({     loading: true,     data: {},     configuration: {},     errors: {},     idToken: "",     client: undefined,   })
         */
        "store": ObservableMap<ProfileStore>;
        "useUnidyAuthEnabled"?: boolean;
    }
}
declare global {
    interface HTMLFlashMessageElement extends Components.FlashMessage, HTMLStencilElement {
    }
    var HTMLFlashMessageElement: {
        prototype: HTMLFlashMessageElement;
        new (): HTMLFlashMessageElement;
    };
    interface HTMLSubmitButtonElement extends Components.SubmitButton, HTMLStencilElement {
    }
    var HTMLSubmitButtonElement: {
        prototype: HTMLSubmitButtonElement;
        new (): HTMLSubmitButtonElement;
    };
    interface HTMLUnidyFieldElement extends Components.UnidyField, HTMLStencilElement {
    }
    var HTMLUnidyFieldElement: {
        prototype: HTMLUnidyFieldElement;
        new (): HTMLUnidyFieldElement;
    };
    interface HTMLUnidyProfileElement extends Components.UnidyProfile, HTMLStencilElement {
    }
    var HTMLUnidyProfileElement: {
        prototype: HTMLUnidyProfileElement;
        new (): HTMLUnidyProfileElement;
    };
    interface HTMLElementTagNameMap {
        "flash-message": HTMLFlashMessageElement;
        "submit-button": HTMLSubmitButtonElement;
        "unidy-field": HTMLUnidyFieldElement;
        "unidy-profile": HTMLUnidyProfileElement;
    }
}
declare namespace LocalJSX {
    interface FlashMessage {
        /**
          * @default ""
         */
        "message"?: string;
        /**
          * @default "info"
         */
        "variant"?: "error" | "success" | "info";
    }
    interface SubmitButton {
    }
    interface UnidyField {
        "field": string;
        /**
          * @default false
         */
        "required"?: boolean;
    }
    interface UnidyProfile {
        "apiKey"?: string;
        "apiUrl"?: string;
        /**
          * @default ""
         */
        "initialData"?: string | Record<string, string>;
        "profileId"?: string;
        /**
          * @default createStore<ProfileStore>({     loading: true,     data: {},     configuration: {},     errors: {},     idToken: "",     client: undefined,   })
         */
        "store"?: ObservableMap<ProfileStore>;
        "useUnidyAuthEnabled"?: boolean;
    }
    interface IntrinsicElements {
        "flash-message": FlashMessage;
        "submit-button": SubmitButton;
        "unidy-field": UnidyField;
        "unidy-profile": UnidyProfile;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "flash-message": LocalJSX.FlashMessage & JSXBase.HTMLAttributes<HTMLFlashMessageElement>;
            "submit-button": LocalJSX.SubmitButton & JSXBase.HTMLAttributes<HTMLSubmitButtonElement>;
            "unidy-field": LocalJSX.UnidyField & JSXBase.HTMLAttributes<HTMLUnidyFieldElement>;
            "unidy-profile": LocalJSX.UnidyProfile & JSXBase.HTMLAttributes<HTMLUnidyProfileElement>;
        }
    }
}
