/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CreateSubscriptionsResponse, CreateSubscriptionsResult } from "@unidy.io/sdk-api-client";
export { CreateSubscriptionsResponse, CreateSubscriptionsResult } from "@unidy.io/sdk-api-client";
export namespace Components {
    interface EmailField {
        "className": string;
        "placeholder": string;
    }
    interface NewsletterCheckbox {
        "checked": boolean;
        "className": string;
        "internalName": string;
        "label": string;
    }
    interface SubmitButton {
        "apiKey": string;
        "apiUrl": string;
        "className": string;
    }
}
export interface SubmitButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSubmitButtonElement;
}
declare global {
    interface HTMLEmailFieldElement extends Components.EmailField, HTMLStencilElement {
    }
    var HTMLEmailFieldElement: {
        prototype: HTMLEmailFieldElement;
        new (): HTMLEmailFieldElement;
    };
    interface HTMLNewsletterCheckboxElement extends Components.NewsletterCheckbox, HTMLStencilElement {
    }
    var HTMLNewsletterCheckboxElement: {
        prototype: HTMLNewsletterCheckboxElement;
        new (): HTMLNewsletterCheckboxElement;
    };
    interface HTMLSubmitButtonElementEventMap {
        "success": CreateSubscriptionsResponse;
        "error": CreateSubscriptionsResult[1];
    }
    interface HTMLSubmitButtonElement extends Components.SubmitButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSubmitButtonElementEventMap>(type: K, listener: (this: HTMLSubmitButtonElement, ev: SubmitButtonCustomEvent<HTMLSubmitButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSubmitButtonElementEventMap>(type: K, listener: (this: HTMLSubmitButtonElement, ev: SubmitButtonCustomEvent<HTMLSubmitButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSubmitButtonElement: {
        prototype: HTMLSubmitButtonElement;
        new (): HTMLSubmitButtonElement;
    };
    interface HTMLElementTagNameMap {
        "email-field": HTMLEmailFieldElement;
        "newsletter-checkbox": HTMLNewsletterCheckboxElement;
        "submit-button": HTMLSubmitButtonElement;
    }
}
declare namespace LocalJSX {
    interface EmailField {
        "className"?: string;
        "placeholder"?: string;
    }
    interface NewsletterCheckbox {
        "checked"?: boolean;
        "className"?: string;
        "internalName"?: string;
        "label"?: string;
    }
    interface SubmitButton {
        "apiKey"?: string;
        "apiUrl"?: string;
        "className"?: string;
        "onError"?: (event: SubmitButtonCustomEvent<CreateSubscriptionsResult[1]>) => void;
        "onSuccess"?: (event: SubmitButtonCustomEvent<CreateSubscriptionsResponse>) => void;
    }
    interface IntrinsicElements {
        "email-field": EmailField;
        "newsletter-checkbox": NewsletterCheckbox;
        "submit-button": SubmitButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "email-field": LocalJSX.EmailField & JSXBase.HTMLAttributes<HTMLEmailFieldElement>;
            "newsletter-checkbox": LocalJSX.NewsletterCheckbox & JSXBase.HTMLAttributes<HTMLNewsletterCheckboxElement>;
            "submit-button": LocalJSX.SubmitButton & JSXBase.HTMLAttributes<HTMLSubmitButtonElement>;
        }
    }
}
