/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EmailField {
        "placeholder": string;
    }
    interface NewsletterCheckbox {
        "checked": boolean;
        "internalName": string;
        "label": string;
    }
    interface SubmitButton {
        "apiKey": string;
        "apiUrl": string;
        "title": string;
    }
}
declare global {
    interface HTMLEmailFieldElement extends Components.EmailField, HTMLStencilElement {
    }
    var HTMLEmailFieldElement: {
        prototype: HTMLEmailFieldElement;
        new (): HTMLEmailFieldElement;
    };
    interface HTMLNewsletterCheckboxElement extends Components.NewsletterCheckbox, HTMLStencilElement {
    }
    var HTMLNewsletterCheckboxElement: {
        prototype: HTMLNewsletterCheckboxElement;
        new (): HTMLNewsletterCheckboxElement;
    };
    interface HTMLSubmitButtonElement extends Components.SubmitButton, HTMLStencilElement {
    }
    var HTMLSubmitButtonElement: {
        prototype: HTMLSubmitButtonElement;
        new (): HTMLSubmitButtonElement;
    };
    interface HTMLElementTagNameMap {
        "email-field": HTMLEmailFieldElement;
        "newsletter-checkbox": HTMLNewsletterCheckboxElement;
        "submit-button": HTMLSubmitButtonElement;
    }
}
declare namespace LocalJSX {
    interface EmailField {
        "placeholder"?: string;
    }
    interface NewsletterCheckbox {
        "checked"?: boolean;
        "internalName"?: string;
        "label"?: string;
    }
    interface SubmitButton {
        "apiKey"?: string;
        "apiUrl"?: string;
        "title"?: string;
    }
    interface IntrinsicElements {
        "email-field": EmailField;
        "newsletter-checkbox": NewsletterCheckbox;
        "submit-button": SubmitButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "email-field": LocalJSX.EmailField & JSXBase.HTMLAttributes<HTMLEmailFieldElement>;
            "newsletter-checkbox": LocalJSX.NewsletterCheckbox & JSXBase.HTMLAttributes<HTMLNewsletterCheckboxElement>;
            "submit-button": LocalJSX.SubmitButton & JSXBase.HTMLAttributes<HTMLSubmitButtonElement>;
        }
    }
}
