/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MissingFieldsData } from "../../profile/store/profile-store";
import { TokenResponse } from "./api/auth";
export namespace Components {
    interface UAuthProvider {
        "componentClassName": string;
    }
    interface UAuthSubmitButton {
        "componentClassName": string;
        "disabled": boolean;
        "for": "email" | "password";
        "text": string;
    }
    interface UConditionalRender {
        "is": "true" | "false";
        "when": string;
    }
    interface UEmailField {
        "componentClassName": string;
        "placeholder": string;
    }
    interface UErrorMessage {
        "componentClassName": string;
        "errorMessages"?: Record<string, string>;
        "for": "email" | "password" | "magicCode" | "general";
    }
    interface UMissingField {
    }
    interface UMissingFieldsSubmitButton {
        "disabled": boolean;
    }
    interface UPasskey {
        "componentClassName": string;
        "disabled": boolean;
        "loadingText": string;
        "text": string;
    }
    interface UPasswordField {
        "componentClassName": string;
        "placeholder": string;
    }
    interface UProfileField {
        "field": string;
    }
    interface ULogoutButton {
        "componentClassName": string;
        "reloadOnSuccess": boolean;
        "text": string;
    }
    interface UResetPasswordButton {
        "componentClassName": string;
        "successMessage": string;
        "text": string;
    }
    interface USigninRoot {
        "componentClassName": string;
    }
    interface USigninStep {
        "alwaysRender": boolean;
        "isActive": () => Promise<boolean>;
        "name": "email" | "verification";
        "submit": () => Promise<void>;
    }
    interface USigninStrategy {
        "componentClassName": string;
        "type": "password" | "magic-code";
    }
    interface USendMagicCodeButton {
        "alreadySentText": string;
        "componentClassName": string;
        "disabled": boolean;
        "text": string;
    }
    interface USocialLoginButton {
        "iconOnly": boolean;
        "provider": | "google"
    | "linkedin"
    | "apple"
    | "discord"
    | "facebook"
    | "unidy";
        "redirectUri": string;
        "text": string;
        "theme": "light" | "dark";
    }
}
export interface UAuthSubmitButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUAuthSubmitButtonElement;
}
export interface ULogoutButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLULogoutButtonElement;
}
export interface UMissingFieldCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUMissingFieldElement;
}
export interface UMissingFieldsSubmitButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUMissingFieldsSubmitButtonElement;
}
export interface USigninRootCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUSigninRootElement;
}
export interface UPasskeyCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUPasskeyElement;
}
export interface UPasswordFieldCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUPasswordFieldElement;
}
export interface UResetPasswordButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUResetPasswordButtonElement;
}
export interface USendMagicCodeButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUSendMagicCodeButtonElement;
}
declare global {
    interface HTMLUAuthProviderElement extends Components.UAuthProvider, HTMLStencilElement {
    }
    var HTMLUAuthProviderElement: {
        prototype: HTMLUAuthProviderElement;
        new (): HTMLUAuthProviderElement;
    };
    interface HTMLUAuthSubmitButtonElement extends Components.UAuthSubmitButton, HTMLStencilElement {
    }
    var HTMLUAuthSubmitButtonElement: {
        prototype: HTMLUAuthSubmitButtonElement;
        new (): HTMLUAuthSubmitButtonElement;
    };
    interface HTMLUConditionalRenderElement extends Components.UConditionalRender, HTMLStencilElement {
    }
    var HTMLUConditionalRenderElement: {
        prototype: HTMLUConditionalRenderElement;
        new (): HTMLUConditionalRenderElement;
    };
    interface HTMLUEmailFieldElement extends Components.UEmailField, HTMLStencilElement {
    }
    var HTMLUEmailFieldElement: {
        prototype: HTMLUEmailFieldElement;
        new (): HTMLUEmailFieldElement;
    };
    interface HTMLUErrorMessageElement extends Components.UErrorMessage, HTMLStencilElement {
    }
    var HTMLUErrorMessageElement: {
        prototype: HTMLUErrorMessageElement;
        new (): HTMLUErrorMessageElement;
    };
    interface HTMLUMissingFieldElement extends Components.UMissingField, HTMLStencilElement {
    }
    var HTMLUMissingFieldElement: {
        prototype: HTMLUMissingFieldElement;
        new (): HTMLUMissingFieldElement;
    };
    interface HTMLUMissingFieldsSubmitButtonElement extends Components.UMissingFieldsSubmitButton, HTMLStencilElement {
    }
    var HTMLUMissingFieldsSubmitButtonElement: {
        prototype: HTMLUMissingFieldsSubmitButtonElement;
        new (): HTMLUMissingFieldsSubmitButtonElement;
    };
    interface HTMLUPasskeyElement extends Components.UPasskey, HTMLStencilElement {
    }
    var HTMLUPasskeyElement: {
        prototype: HTMLUPasskeyElement;
        new (): HTMLUPasskeyElement;
    };
    interface HTMLUPasswordFieldElement extends Components.UPasswordField, HTMLStencilElement {
    }
    var HTMLUPasswordFieldElement: {
        prototype: HTMLUPasswordFieldElement;
        new (): HTMLUPasswordFieldElement;
    };
    interface HTMLUProfileFieldElement extends Components.UProfileField, HTMLStencilElement {
    }
    var HTMLUProfileFieldElement: {
        prototype: HTMLUProfileFieldElement;
        new (): HTMLUProfileFieldElement;
    };
    interface HTMLULogoutButtonElement extends Components.ULogoutButton, HTMLStencilElement {
    }
    var HTMLULogoutButtonElement: {
        prototype: HTMLULogoutButtonElement;
        new (): HTMLULogoutButtonElement;
    };
    interface HTMLUResetPasswordButtonElement extends Components.UResetPasswordButton, HTMLStencilElement {
    }
    var HTMLUResetPasswordButtonElement: {
        prototype: HTMLUResetPasswordButtonElement;
        new (): HTMLUResetPasswordButtonElement;
    };
    interface HTMLUSigninRootElement extends Components.USigninRoot, HTMLStencilElement {
    }
    var HTMLUSigninRootElement: {
        prototype: HTMLUSigninRootElement;
        new (): HTMLUSigninRootElement;
    };
    interface HTMLUSigninStepElement extends Components.USigninStep, HTMLStencilElement {
    }
    var HTMLUSigninStepElement: {
        prototype: HTMLUSigninStepElement;
        new (): HTMLUSigninStepElement;
    };
    interface HTMLUSigninStrategyElement extends Components.USigninStrategy, HTMLStencilElement {
    }
    var HTMLUSigninStrategyElement: {
        prototype: HTMLUSigninStrategyElement;
        new (): HTMLUSigninStrategyElement;
    };
    interface HTMLUSendMagicCodeButtonElement extends Components.USendMagicCodeButton, HTMLStencilElement {
    }
    var HTMLUSendMagicCodeButtonElement: {
        prototype: HTMLUSendMagicCodeButtonElement;
        new (): HTMLUSendMagicCodeButtonElement;
    };
    interface HTMLUSocialLoginButtonElement extends Components.USocialLoginButton, HTMLStencilElement {
    }
    var HTMLUSocialLoginButtonElement: {
        prototype: HTMLUSocialLoginButtonElement;
        new (): HTMLUSocialLoginButtonElement;
    };
    interface HTMLElementTagNameMap {
        "u-auth-provider": HTMLUAuthProviderElement;
        "u-auth-submit-button": HTMLUAuthSubmitButtonElement;
        "u-conditional-render": HTMLUConditionalRenderElement;
        "u-email-field": HTMLUEmailFieldElement;
        "u-error-message": HTMLUErrorMessageElement;
        "u-missing-field": HTMLUMissingFieldElement;
        "u-missing-fields-submit-button": HTMLUMissingFieldsSubmitButtonElement;
        "u-passkey": HTMLUPasskeyElement;
        "u-password-field": HTMLUPasswordFieldElement;
        "u-profile-field": HTMLUProfileFieldElement;
        "u-logout-button": HTMLULogoutButtonElement;
        "u-reset-password-button": HTMLUResetPasswordButtonElement;
        "u-signin-root": HTMLUSigninRootElement;
        "u-signin-step": HTMLUSigninStepElement;
        "u-signin-strategy": HTMLUSigninStrategyElement;
        "u-send-magic-code-button": HTMLUSendMagicCodeButtonElement;
        "u-social-login-button": HTMLUSocialLoginButtonElement;
    }
}
declare namespace LocalJSX {
    interface UAuthProvider {
        "componentClassName"?: string;
    }
    interface UAuthSubmitButton {
        "componentClassName"?: string;
        "disabled"?: boolean;
        "for": "email" | "password";
        "text"?: string;
    }
    interface UConditionalRender {
        "is": "true" | "false";
        "when": string;
    }
    interface UEmailField {
        "componentClassName"?: string;
        "placeholder"?: string;
    }
    interface UErrorMessage {
        "componentClassName"?: string;
        "errorMessages"?: Record<string, string>;
        "for": "email" | "password" | "magicCode" | "general";
    }
    interface UMissingField {
    }
    interface UMissingFieldsSubmitButton {
        "disabled"?: boolean;
    }
    interface UPasskey {
        "componentClassName"?: string;
        "disabled"?: boolean;
        "loadingText"?: string;
        "text"?: string;
    }
    interface UPasswordField {
        "componentClassName"?: string;
        "placeholder"?: string;
    }
    interface UProfileField {
        "field": string;
    }
    interface ULogoutButton {
        "componentClassName"?: string;
        "onLogout"?: (event: ULogoutButtonCustomEvent<void>) => void;
        "reloadOnSuccess"?: boolean;
        "text"?: string;
    }
    interface UResetPasswordButton {
        "componentClassName"?: string;
        "successMessage"?: string;
        "text"?: string;
    }
    interface USigninRoot {
        "componentClassName"?: string;
        "onAuthEvent"?: (event: USigninRootCustomEvent<TokenResponse>) => void;
        "onErrorEvent"?: (event: USigninRootCustomEvent<{ error: string }>) => void;
    }
    interface USigninStep {
        "alwaysRender"?: boolean;
        "name": "email" | "verification";
    }
    interface USigninStrategy {
        "componentClassName"?: string;
        "type": "password" | "magic-code";
    }
    interface USendMagicCodeButton {
        "alreadySentText"?: string;
        "componentClassName"?: string;
        "disabled"?: boolean;
        "text"?: string;
    }
    interface USocialLoginButton {
        "iconOnly"?: boolean;
        "provider"?: | "google"
    | "linkedin"
    | "apple"
    | "discord"
    | "facebook"
    | "unidy";
        "redirectUri"?: string;
        "text"?: string;
        "theme"?: "light" | "dark";
    }
    interface IntrinsicElements {
        "u-auth-provider": UAuthProvider;
        "u-auth-submit-button": UAuthSubmitButton;
        "u-conditional-render": UConditionalRender;
        "u-email-field": UEmailField;
        "u-error-message": UErrorMessage;
        "u-missing-field": UMissingField;
        "u-missing-fields-submit-button": UMissingFieldsSubmitButton;
        "u-passkey": UPasskey;
        "u-password-field": UPasswordField;
        "u-profile-field": UProfileField;
        "u-logout-button": ULogoutButton;
        "u-reset-password-button": UResetPasswordButton;
        "u-signin-root": USigninRoot;
        "u-signin-step": USigninStep;
        "u-signin-strategy": USigninStrategy;
        "u-send-magic-code-button": USendMagicCodeButton;
        "u-social-login-button": USocialLoginButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "u-auth-provider": LocalJSX.UAuthProvider & JSXBase.HTMLAttributes<HTMLUAuthProviderElement>;
            "u-auth-submit-button": LocalJSX.UAuthSubmitButton & JSXBase.HTMLAttributes<HTMLUAuthSubmitButtonElement>;
            "u-conditional-render": LocalJSX.UConditionalRender & JSXBase.HTMLAttributes<HTMLUConditionalRenderElement>;
            "u-email-field": LocalJSX.UEmailField & JSXBase.HTMLAttributes<HTMLUEmailFieldElement>;
            "u-error-message": LocalJSX.UErrorMessage & JSXBase.HTMLAttributes<HTMLUErrorMessageElement>;
            "u-missing-field": LocalJSX.UMissingField & JSXBase.HTMLAttributes<HTMLUMissingFieldElement>;
            "u-missing-fields-submit-button": LocalJSX.UMissingFieldsSubmitButton & JSXBase.HTMLAttributes<HTMLUMissingFieldsSubmitButtonElement>;
            "u-passkey": LocalJSX.UPasskey & JSXBase.HTMLAttributes<HTMLUPasskeyElement>;
            "u-password-field": LocalJSX.UPasswordField & JSXBase.HTMLAttributes<HTMLUPasswordFieldElement>;
            "u-profile-field": LocalJSX.UProfileField & JSXBase.HTMLAttributes<HTMLUProfileFieldElement>;
            "u-logout-button": LocalJSX.ULogoutButton & JSXBase.HTMLAttributes<HTMLULogoutButtonElement>;
            "u-reset-password-button": LocalJSX.UResetPasswordButton & JSXBase.HTMLAttributes<HTMLUResetPasswordButtonElement>;
            "u-signin-root": LocalJSX.USigninRoot & JSXBase.HTMLAttributes<HTMLUSigninRootElement>;
            "u-signin-step": LocalJSX.USigninStep & JSXBase.HTMLAttributes<HTMLUSigninStepElement>;
            "u-signin-strategy": LocalJSX.USigninStrategy & JSXBase.HTMLAttributes<HTMLUSigninStrategyElement>;
            "u-send-magic-code-button": LocalJSX.USendMagicCodeButton & JSXBase.HTMLAttributes<HTMLUSendMagicCodeButtonElement>;
            "u-social-login-button": LocalJSX.USocialLoginButton & JSXBase.HTMLAttributes<HTMLUSocialLoginButtonElement>;
        }
    }
}